### ISSUE TITLE
SQLlite Error with MC 1.11

### ISSUE THREAD

**Issue by EnderSandman** [PyvesB/AdvancedAchievements#102]
[12:06:25] [Server thread/ERROR]: Error occurred while enabling AdvancedAchievements v3.0.5 (Is it up to date?)
java.lang.NoClassDefFoundError: org/sqlite/NativeDB
        at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_101]
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941) ~[?:1.8.0_101]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824) ~[?:1.8.0_101]
        at java.lang.Runtime.load0(Runtime.java:809) ~[?:1.8.0_101]
        at java.lang.System.load(System.java:1086) ~[?:1.8.0_101]
        at org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:268) ~[spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
        at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:304) ~[spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
        at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64) ~[spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
        at org.sqlite.core.NativeDB.load(NativeDB.java:56) ~[spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
        at org.sqlite.core.CoreConnection.open(CoreConnection.java:211) ~[spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
        at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76) ~[spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24) ~[spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24) ~[spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45) ~[spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
        at org.sqlite.JDBC.createConnection(JDBC.java:114) ~[spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
        at org.sqlite.JDBC.connect(JDBC.java:88) ~[spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
        at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_101]
        at java.sql.DriverManager.getConnection(DriverManager.java:270) ~[?:1.8.0_101]
        at com.hm.achievement.db.SQLDatabaseManager.createSQLiteConnection(SQLDatabaseManager.java:415) ~[?:?]
        at com.hm.achievement.db.SQLDatabaseManager.getSQLConnection(SQLDatabaseManager.java:388) ~[?:?]
        at com.hm.achievement.db.SQLDatabaseManager.initialise(SQLDatabaseManager.java:87) ~[?:?]
        at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:401) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.jar:git-Spigot-0f17cfb-a0d5a84]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.ClassNotFoundException: org.sqlite.NativeDB
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_101]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_101]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
        ... 33 more

**Comment by PyvesB** [comment]
Hello,

There are already quite a lot of servers using Advanced Achievements with Minecraft 1.11, and there haven't been any complaints so far. This is therefore more likely a problem that is not directly caused by Advanced Achievements.

Could you ensure that you are using the latest official build of Spigot, and that you have an up-to-date version of  SQLite on your server. Also please update or remove any other plugins making use of a SQLite database. Quoting a discussion from Spigot, some plugins are causing others to fail:

> You don't run LWC by any chance? Because LWC downloads an old driver and loads that into spigot, crashing SQLite for all plugins.
> Try to run an updated version of LWC (i use https://www.spigotmc.org/resources/lwc-unofficial-entity-locking.2162) and delete the /plugins/LWC/lib folder...
> 
> Edit: Maybe some other plugin behaves just as bad. What you should probably do before posting here: Remove all plugins and add them back one by one, see if it works.

Cheers,

Pyves

**Comment by EnderSandman** [comment]
The LWC thing fixed my issues.  Thanks very much for the help!
