### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by ghost** [PyvesB/AdvancedAchievements#1082]
### 🎆 Advanced Achievements version

7.2.5

### 🖥 Server version

Airplane-1.17 Build 92

### 🚰 Spigot username

XragonX147

### 𝑾 Wiki read

- [X] I have read the Wiki.

### 📁 Existing issues

- [X] I have searched existing issues.

### 🐛 Description

Hi, 

i created an Achievement with the goal, too mine new 1.17 deepslate Blocks.
Everytime someone Mine those listed blocks, there is an error in the logs.

Thanks for Help :)

### 📄 Server logs

[07:21:37] [Craft Scheduler Thread - 23 - AdvancedAchievements/ERROR]: [AdvancedAchievements] Database write error while batching statistic updates:
com.hm.h2.jdbc.JdbcBatchUpdateException: (Message 22001 not found); SQL statement:
REPLACE INTO breaks VALUES ('6ecb0771-63d1-4f68-9a4f-db34d443684e', 'deepslate_copper_ore|deepslate_gold_ore|deepslate_diamond_ore|deepslate_lapis_ore|deepslate_coal_ore|deepslate_iron_ore|deepslate_redstone_ore|deepslate_emerald_ore', 4) [22001-200]
	at com.hm.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:781) ~[AdvancedAchievements.jar:?]
	at com.hm.achievement.db.AsyncCachedRequestsSender.lambda$sendBatchedRequests$0(AsyncCachedRequestsSender.java:67) ~[AdvancedAchievements.jar:?]
	at com.hm.achievement.db.SQLWriteOperation.attemptWrites(SQLWriteOperation.java:45) [AdvancedAchievements.jar:?]
	at com.hm.achievement.db.AsyncCachedRequestsSender.sendBatchedRequests(AsyncCachedRequestsSender.java:72) [AdvancedAchievements.jar:?]
	at com.hm.achievement.db.AsyncCachedRequestsSender.run(AsyncCachedRequestsSender.java:44) [AdvancedAchievements.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) [patched_1.17.1.jar:git-Airplane-92]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [patched_1.17.1.jar:git-Airplane-92]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.17.1.jar:git-Airplane-92]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]

### ⚙ Configuration

  deepslate_copper_ore|deepslate_gold_ore|deepslate_diamond_ore|deepslate_lapis_ore|deepslate_coal_ore|deepslate_iron_ore|deepslate_redstone_ore|deepslate_emerald_ore:
    1000:
      Goal: Baue neue 1.17 Blöcke ab.
      Message: Du hast 1000 neue 1.17 Blöcke abgebaut
      Name: break_1000_1.17_any
      DisplayName: Update Erkunder 1
      Type: normal
      Reward:
        Command:
          Execute: "f mp PLAYER 1"
          Display: "&7Du bekommst &6+1 Power"

**Comment by PyvesB** [comment]
Hello @XragonX147 ! 👋🏻 

This sounds similar to #1080. Have you sufficiently increased the value of `TableMaxSizeOfGroupedSubcategories`?
