### ISSUE TITLE
Database connection error?

### ISSUE THREAD

**Issue by wattywatty14** [PyvesB/AdvancedAchievements#132]
I get this error when trying to connect to my database. I don't understand.

```
`1 18:54:34 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
19.01 18:54:34 [Server] INFO at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:422) [AdvancedAchievements.jar:?]
19.01 18:54:34 [Server] INFO at com.hm.achievement.db.SQLDatabaseManager.initialise(SQLDatabaseManager.java:91) [AdvancedAchievements.jar:?]
19.01 18:54:34 [Server] INFO at com.hm.achievement.db.SQLDatabaseManager.getSQLConnection(SQLDatabaseManager.java:398) [AdvancedAchievements.jar:?]
19.01 18:54:34 [Server] INFO at com.hm.achievement.db.SQLDatabaseManager.createRemoteSQLConnection(SQLDatabaseManager.java:439) ~[AdvancedAchievements.jar:?]
19.01 18:54:34 [Server] INFO at java.sql.DriverManager.getConnection(DriverManager.java:270) ~[?:1.8.0_111]
19.01 18:54:34 [Server] INFO at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_111]
19.01 18:54:34 [Server] INFO at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
19.01 18:54:34 [Server] INFO at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
19.01 18:54:34 [Server] INFO at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
19.01 18:54:34 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_111]
19.01 18:54:34 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_111]
19.01 18:54:34 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_111]
19.01 18:54:34 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_111]
19.01 18:54:34 [Server] INFO at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
19.01 18:54:34 [Server] INFO at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
19.01 18:54:34 [Server] INFO at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2089) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
19.01 18:54:34 [Server] INFO at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2164) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
19.01 18:54:34 [Server] INFO at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:862) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
19.01 18:54:34 [Server] INFO at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
19.01 18:54:34 [Server] INFO at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
19.01 18:54:34 [Server] INFO at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
19.01 18:54:34 [Server] INFO at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
19.01 18:54:34 [Server] INFO at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
19.01 18:54:34 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_111]
19.01 18:54:34 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_111]
19.01 18:54:34 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_111]
19.01 18:54:34 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_111]
19.01 18:54:34 [Server] INFO com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
19.01 18:54:34 [Server] ERROR [AdvancedAchievements] Error while attempting to retrieve connection to database: 
19.01 18:54:30 [Server] INFO [AdvancedAchievements] Initialising database and launching scheduled tasks...`
```

**Comment by PyvesB** [comment]
Hello,

It seems as if either the _Database_, _User_ or _Password_ parameter in your configuration is wrong, and the plugin can therefore not connect to your database. Have you double checked them?

Cheers,

Pyves
