### ISSUE TITLE
Error upon loading plugin

### ISSUE THREAD

**Issue by HeartlessWind** [PyvesB/AdvancedAchievements#144]
I get this error every time I try to start my server. Currently running Minecraft version 1.11.2.

[09:47:30 INFO]: [AdvancedAchievements] Initialising database and launching scheduled tasks...
[09:47:30 WARN]: Failed to load native library:sqlite-3.16.1-ee74f1cf-1470-414d-888f-709306112c2c-libsqlitejdbc.so. osinfo: Linux/x86_64
[09:47:30 WARN]: java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.16.1-ee74f1cf-1470-414d-888f-709306112c2c-libsqlitejdbc.so: /tmp/sqlite-3.16.1-ee74f1cf-1470-414d-888f-709306112c2c-libsqlitejdbc.so: failed to map segment from shared object: Operation not permitted
[09:47:30 INFO]: [AdvancedAchievements] Backing up database file...
[09:47:30 INFO]: [AdvancedAchievements] Loaded 50 achievements in 45 categories.
[09:47:30 INFO]: [AdvancedAchievements] Successfully created database file.
[09:47:30 ERROR]: Error occurred while enabling AdvancedAchievements v4.2 (Is it up to date?)
at org.sqlite.core.NativeDB._open_utf8(Native Method) ~[spigot-R0.1-d4f98a3918e-cb61ac0404a-2eb7b9fd887.jar:git-Spigot-d4f98a3-cb61ac0]
java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
at org.sqlite.core.NativeDB._open(NativeDB.java:71) ~[spigot-R0.1-d4f98a3918e-cb61ac0404a-2eb7b9fd887.jar:git-Spigot-d4f98a3-cb61ac0]
at org.sqlite.core.DB.open(DB.java:174) ~[spigot-R0.1-d4f98a3918e-cb61ac0404a-2eb7b9fd887.jar:git-Spigot-d4f98a3-cb61ac0]
at org.sqlite.core.CoreConnection.open(CoreConnection.java:220) ~[spigot-R0.1-d4f98a3918e-cb61ac0404a-2eb7b9fd887.jar:git-Spigot-d4f98a3-cb61ac0]
at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76) ~[spigot-R0.1-d4f98a3918e-cb61ac0404a-2eb7b9fd887.jar:git-Spigot-d4f98a3-cb61ac0]
at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:26) ~[spigot-R0.1-d4f98a3918e-cb61ac0404a-2eb7b9fd887.jar:git-Spigot-d4f98a3-cb61ac0]
at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_45]
at org.sqlite.JDBC.createConnection(JDBC.java:114) ~[spigot-R0.1-d4f98a3918e-cb61ac0404a-2eb7b9fd887.jar:git-Spigot-d4f98a3-cb61ac0]
at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24) ~[spigot-R0.1-d4f98a3918e-cb61ac0404a-2eb7b9fd887.jar:git-Spigot-d4f98a3-cb61ac0]
at com.hm.achievement.db.SQLDatabaseManager.initialise(SQLDatabaseManager.java:90) ~[?:?]
at com.hm.achievement.db.SQLDatabaseManager.getSQLConnection(SQLDatabaseManager.java:399) ~[?:?]
at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:431) ~[?:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-R0.1-d4f98a3918e-cb61ac0404a-2eb7b9fd887.jar:git-Spigot-d4f98a3-cb61ac0]
at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45) ~[spigot-R0.1-d4f98a3918e-cb61ac0404a-2eb7b9fd887.jar:git-Spigot-d4f98a3-cb61ac0]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-R0.1-d4f98a3918e-cb61ac0404a-2eb7b9fd887.jar:git-Spigot-d4f98a3-cb61ac0]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-R0.1-d4f98a3918e-cb61ac0404a-2eb7b9fd887.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-R0.1-d4f98a3918e-cb61ac0404a-2eb7b9fd887.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-R0.1-d4f98a3918e-cb61ac0404a-2eb7b9fd887.jar:git-Spigot-d4f98a3-cb61ac0]
at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-R0.1-d4f98a3918e-cb61ac0404a-2eb7b9fd887.jar:git-Spigot-d4f98a3-cb61ac0]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-R0.1-d4f98a3918e-cb61ac0404a-2eb7b9fd887.jar:git-Spigot-d4f98a3-cb61ac0]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[09:47:30 INFO]: [MobHunting] Enabling MobHunting v4.5.3
at org.sqlite.JDBC.connect(JDBC.java:88) ~[spigot-R0.1-d4f98a3918e-cb61ac0404a-2eb7b9fd887.jar:git-Spigot-d4f98a3-cb61ac0]
java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-R0.1-d4f98a3918e-cb61ac0404a-2eb7b9fd887.jar:git-Spigot-d4f98a3-cb61ac0]

**Comment by PyvesB** [comment]
Hello,

First time I see such an error with the plugin, let's investigate!

- Could you please run the `mount | grep /tmp` command and print its output here?
- Have you got any other plugins making use of the SQLite database?
- Has this error always occurred since you first installed the plugin, or did it only start happening recently?

Cheers,

Pyves

**Comment by HeartlessWind** [comment]
Do I need to run that through my server console? I currently get a command unknown error.  If it helps I am running this through Nodecraft hosting.

One other plugin seems to be throwing the same error or at least similar. So perhaps it is something else entirely. This is my first time trying to use this plugin. So first time happening.

**Comment by PyvesB** [comment]
You have to run the command on your server's machine, but not directly in the game console. ;-)

**Comment by HeartlessWind** [comment]
It appears this was actually an issue with my host not the plugin itself. Thank you for looking into it!

**Comment by PyvesB** [comment]
No problem, enjoy using the plugin!
