### ISSUE TITLE
Crash while charge the plug

### ISSUE THREAD

**Issue by Wikijito7** [PyvesB/AdvancedAchievements#20]
I started my server, then it sent the following crash:

Error occurred while enabling AdvancedAchievements v2.5.1 (Is it up to date?)
java.lang.NullPointerException
	at com.hm.achievement.command.StatsCommand.<init>(StatsCommand.java:18) ~[?:?]
	at com.hm.achievement.AdvancedAchievements.configurationLoad(AdvancedAchievements.java:450) ~[?:?]
	at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:162) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-d884ab3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.2.jar:git-Spigot-e6f93f4-d884ab3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.2.jar:git-Spigot-e6f93f4-d884ab3]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.2.jar:git-Spigot-e6f93f4-d884ab3]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.2.jar:git-Spigot-e6f93f4-d884ab3]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.reload(CraftServer.java:745) [spigot-1.9.2.jar:git-Spigot-e6f93f4-d884ab3]
	at org.bukkit.Bukkit.reload(Bukkit.java:539) [spigot-1.9.2.jar:git-Spigot-e6f93f4-d884ab3]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot-1.9.2.jar:git-Spigot-e6f93f4-d884ab3]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.9.2.jar:git-Spigot-e6f93f4-d884ab3]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot-1.9.2.jar:git-Spigot-e6f93f4-d884ab3]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchServerCommand(CraftServer.java:631) [spigot-1.9.2.jar:git-Spigot-e6f93f4-d884ab3]
	at net.minecraft.server.v1_9_R1.DedicatedServer.aL(DedicatedServer.java:438) [spigot-1.9.2.jar:git-Spigot-e6f93f4-d884ab3]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:401) [spigot-1.9.2.jar:git-Spigot-e6f93f4-d884ab3]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-e6f93f4-d884ab3]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-e6f93f4-d884ab3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

**Comment by PyvesB** [comment]
Hello,

Have you deleted a main category from the configuration file?

**Comment by Wikijito7** [comment]
Hi

I solved it deleting the file.

The problem was caused because I ported the old config of the 1.8 with the 1.9 plugin, then it deleted all and started to crash like so.

**Comment by PyvesB** [comment]
Ok, great! As stated in the FAQ (https://github.com/PyvesB/AdvancedAchievements/wiki/FAQ-(Frequently-Asked-Questions)), you must not delete any main category; I recommend taking a look at it, there's a lot of useful information.

I'm therefore closing this issue, feel free to star the project if you wish! ;-)

Cheers,

Pyves
