### ISSUE TITLE
KCauldron version 1.7.10-R0.1-SNAPSHOT & GRASS_PATH

### ISSUE THREAD

**Issue by LLIaMMaH** [PyvesB/AdvancedAchievements#21]
This server is running KCauldron version 1.7.10-R0.1-SNAPSHOT (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
....
[18:48:55 ERROR]: Error occurred while enabling AdvancedAchievements v2.5 (Is it up to date?)
java.lang.NoSuchFieldError: **GRASS_PATH**
        at com.hm.achievement.command.ListCommand.<clinit>(ListCommand.java:44) ~[?:?]
        at com.hm.achievement.AdvancedAchievements.configurationLoad(AdvancedAchievements.java:452) ~[?:?]
        at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:162) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]

http://minecraft.gamepedia.com/Grass_Path
History (Official release)
1.9 - 15w31a - Added grass path.
1.9 - 15w31c - Changed collision height to 15⁄16 of a block.

**Comment by PyvesB** [comment]
Hello,

Please update to the latest version of the plugin, it will most likely fix this issue.

> Changes in version 2.5.1:
> 
> Fix: fixed incompatibility with Minecraft versions prior to 1.9.

Cheers,

Pyves

**Comment by LLIaMMaH** [comment]
Thank you for this correction. So much better.

**Comment by PyvesB** [comment]
No problem. Feel free to star the project if you wish. ;-)

**Comment by LLIaMMaH** [comment]
Thanks for the suggestion.
