### ISSUE TITLE
 Could not load 'plugins/AdvancedAchievements.jar' Invalid plugin.yml

### ISSUE THREAD

**Issue by FrozenBeard** [PyvesB/AdvancedAchievements#227]
Downloaded for the first time, and it won't load.

```
[19:24:06] [Server thread/ERROR]: Could not load 'plugins/AdvancedAchievements.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:158) ~[patched_1.12.jar:git-Paper-1153]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136) [patched_1.12.jar:git-Paper-1153]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:303) [patched_1.12.jar:git-Paper-1153]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:223) [patched_1.12.jar:git-Paper-1153]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [patched_1.12.jar:git-Paper-1153]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_131]
	at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[?:1.8.0_131]
	at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[?:1.8.0_131]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_131]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:146) ~[patched_1.12.jar:git-Paper-1153]
	... 5 more
```

**Comment by PyvesB** [comment]
Hello FrozenBeard,

Where did you download the plugin? Are you using the latest version? Have you tried updating your Paper Spigot build? If it still doesn't work, could you please attach the _.jar_ file you are trying to use (you will need to zip it so that GitHub can accept it)?

Cheers,

Pyves

**Comment by FrozenBeard** [comment]
I downloaded from https://www.spigotmc.org/resources/advanced-achievements.6239/
I have the latest Paper-Spigot yes.
I downloaded from BukkitDev instead and strangely it worked.

**Comment by PyvesB** [comment]
Probably an error during the download. Closing the issue. ;-)
