### ISSUE TITLE
java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/EntityPlayer

### ISSUE THREAD

**Issue by LLIaMMaH** [PyvesB/AdvancedAchievements#23]
AdvancedAchievements v2.5.1
`[07:23:58 INFO]: [AdvancedAchievements] Player LLIaMMaH received the achievement: Big Walker
[07:23:58 ERROR]: [AdvancedAchievements] Errors while trying to display achievement screen title. Is your server up-to-date?
[07:23:58 WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/EntityPlayer
[07:23:58 WARN]:        at java.lang.Class.forName0(Native Method)
[07:23:58 WARN]:        at java.lang.Class.forName(Unknown Source)
[07:23:58 WARN]:        at com.hm.achievement.particle.PacketSender.sendTitlePacket(PacketSender.java:61)
[07:23:58 WARN]:        at com.hm.achievement.AchievementDisplay.displayAchievement(AchievementDisplay.java:103)
[07:23:58 WARN]:        at com.hm.achievement.runnable.AchieveDistanceRunnable.awardDistanceAchievement(AchieveDistanceRunnable.java:332)
[07:23:58 WARN]:        at com.hm.achievement.runnable.AchieveDistanceRunnable.refreshDistance(AchieveDistanceRunnable.java:298)
[07:23:58 WARN]:        at com.hm.achievement.runnable.AchieveDistanceRunnable.run(AchieveDistanceRunnable.java:159)
[07:23:58 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[07:23:58 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
[07:23:58 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:873)
[07:23:58 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[07:23:58 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[07:23:58 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[07:23:58 WARN]:        at java.lang.Thread.run(Unknown Source)`

`[07:26:29 INFO]: [AdvancedAchievements] Player LLIaMMaH received the achievement: ┬з4╨Э╨╛╨▓╨╛╨▒╤А╨░╨╜╨╡╤Ж
[07:26:29 ERROR]: [AdvancedAchievements] Errors while trying to display achievement screen title. Is your server up-to-date?
[07:26:29 WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/EntityPlayer
[07:26:29 WARN]:        at java.lang.Class.forName0(Native Method)
[07:26:29 WARN]:        at java.lang.Class.forName(Unknown Source)
[07:26:29 WARN]:        at com.hm.achievement.particle.PacketSender.sendTitlePacket(PacketSender.java:61)
[07:26:29 WARN]:        at com.hm.achievement.AchievementDisplay.displayAchievement(AchievementDisplay.java:103)
[07:26:29 WARN]:        at com.hm.achievement.listener.AchieveXPListener.onPlayerExpChange(AchieveXPListener.java:71)
[07:26:29 WARN]:        at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source)
[07:26:29 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[07:26:29 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[07:26:29 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334)
[07:26:29 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[07:26:29 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
[07:26:29 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492)
[07:26:29 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerLevelChangeEvent(CraftEventFactory.java:653)
[07:26:29 WARN]:        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:453)
[07:26:29 WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:482)
[07:26:29 WARN]:        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36)
[07:26:29 WARN]:        at net.minecraft.network.play.client.C03PacketPlayer$C05PacketPlayerLook.func_148833_a(C03PacketPlayer.java:182)
[07:26:29 WARN]:        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
[07:26:29 WARN]:        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[07:26:29 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991)
[07:26:29 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[07:26:29 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[07:26:29 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[07:26:29 WARN]:        at java.lang.Thread.run(Unknown Source)`

In version 2.5 there was no error.

**Comment by PyvesB** [comment]
Hello,

Screen titles did not exist back in Minecraft 1.7.4, they were "only" introduced around two years ago in a snapshot version of the game. You should therefore set TitleScreen to false in the configuration. ;-)

Cheers,

Pyves

**Comment by LLIaMMaH** [comment]
Thank you very much helped. Error is no more.

**Comment by PyvesB** [comment]
You're welcome, issue closed.

Cheers,

Pyves
