### ISSUE TITLE
PlayerPickupItemEvent deprecated error

### ISSUE THREAD

**Issue by mat41997** [PyvesB/AdvancedAchievements#247]
timings
https://timings.aikar.co/?id=99b9ab2c1abe4dbea62a68ddb2d20342

logs
```
[21:06:31] [Server thread/WARN]: [AdvancedAchievements] "AdvancedAchievements v5.2.7" has registered a listener for org.bukkit.event.player.PlayerPickupItemEvent on method "public void com.hm.achievement.listener.AchievePickupListener.onPlayerPickupItem(org.bukkit.event.player.PlayerPickupItemEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [DarkPyves].
org.bukkit.plugin.AuthorNagException: null
	at org.bukkit.plugin.java.JavaPluginLoader.createRegisteredListeners(JavaPluginLoader.java:277) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:545) [patched_1.12.2.jar:git-Paper-1222]
	at com.hm.achievement.AdvancedAchievements.registerListeners(AdvancedAchievements.java:617) [AdvancedAchievements.jar:?]
	at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:220) [AdvancedAchievements.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by PyvesB** [comment]
Hello mat41997,

This is a regression from Spigot. I'll implement a workaround to fix it and keep the plugin compatible all the way from version 1.7.9 to 1.12.1, as they are generally unhelpful in fixing/reverting such regressions.

Cheers,

Pyves

**Comment by PyvesB** [comment]
Hello,

Writing up a new message after some additional investigation. I am not able to reproduce this in Spigot, this must therefore be an issue that only occurs with Paper (which I believe you are using).Such a warning/exception should probably not be thrown, as `@Warning(false)` is set on the `PlayerPickupItemEvent` class. Could you please open an issue in the [PaperSpigot  repository](https://github.com/PaperMC/Paper/issues) by providing all the information they need in the template, and share the link here so I can add any additional information?

Cheers,

Pyves

**Comment by Platinteufel** [comment]
Sounds weird, I will test it with Paper tomorrow. :)
Is there any reason why you don't use the new `EntityPickupItemEvent`?

**Comment by mat41997** [comment]
bukkit.yml > deprecated-verbose > true

**Comment by PyvesB** [comment]
@Platinteufel `EntityPickupItemEvent` was only created a couple of months ago. I keep on using it to support all Minecraft versions from 1.7.9 through to 1.12 (only the last 1.12 versions, as well as 1.12.1 and 1.12.2 have it). The other way to do it would be to create two separate classes, each one using a different event and detect during runtime whether `EntityPickupItemEvent` is available, but this is somewhat impractical. `EntityPickupItemEvent` is also more general, I would have to do filtering and casting to make sure the event I receive is about a player, and not a zombie or skeleton for instance, which makes me loose a tiny bit of performance. :-)

@mat41997 indeed, I get it on Spigot as well with that option enabled. I didn't know about this option, and after some more digging in the Bukkit source, it makes sense. Any reason why you use verbose logging? This will make your server do more computations on startup and generate chattier logs, without any benefit for you.
