### ISSUE TITLE
1.7.10 Gui interface error

### ISSUE THREAD

**Issue by Xiazihong** [PyvesB/AdvancedAchievements#261]
All Gui interface in the process of trying to open this error will appear

[19:09:21] [Server thread/ERROR]: Error occurred while enabling AdvancedAchievements v5.3.3 (Is it up to date?)
java.lang.NoSuchFieldError: BARRIER
	at com.hm.achievement.gui.MainGUI.<clinit>(MainGUI.java:23) ~[?:?]
	at com.hm.achievement.AdvancedAchievements.initialiseGUIs(AdvancedAchievements.java:697) ~[?:?]
	at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:233) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:420) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:352) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:507) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:481) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:441) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:353) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]

**Comment by PyvesB** [comment]
Hello Xiazihong,

Please go through the [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki), in particular the installation guide. 😉

Cheers,

Pyves
