### ISSUE TITLE
SQL error while retrieving playedtime stats

### ISSUE THREAD

**Issue by EncryptSL** [PyvesB/AdvancedAchievements#279]
Hello this error i found when first player join on server.

`[12:02:23] [Server thread/ERROR]: [AdvancedAchievements] SQL error while retrieving playedtime stats: 
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 152,494 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_144]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_144]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3559) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3459) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3900) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2483) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2441) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	at com.hm.achievement.db.AbstractSQLDatabaseManager.getNormalAchievementAmount(AbstractSQLDatabaseManager.java:478) ~[?:?]
	at com.hm.achievement.db.DatabaseCacheManager.getAndIncrementStatisticAmount(DatabaseCacheManager.java:116) ~[?:?]
	at com.hm.achievement.runnable.AchievePlayTimeRunnable.updateTime(AchievePlayTimeRunnable.java:77) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) [?:1.8.0_144]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) [?:1.8.0_144]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) [?:1.8.0_144]
	at com.hm.achievement.runnable.AchievePlayTimeRunnable.run(AchievePlayTimeRunnable.java:48) [AdvancedAchievements%20(2).jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-3d850ec-809c399]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3011) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3469) ~[spigot.jar:git-Spigot-3d850ec-809c399]
	... 21 more`

**Comment by PyvesB** [comment]
Hello EncryptSL,

Does this only happen with `PlayedTime` statistics? What do you mean by "when first player join on server"? After every server restart for instance?

Cheers,

Pyves

**Comment by EncryptSL** [comment]
Hi, when the server restarts and the player connects. First of all players ;).

**Comment by PyvesB** [comment]
What are the values of the `wait_timeout`, `interactive_timeout ` and `connect_timeout ` of your MySQL database?

**Comment by PyvesB** [comment]
I'm performed a few changes over the week-end to make the database read operations more robust, this may help you out as well. Would you like to give this test version a try?

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/1565874/AdvancedAchievements.zip)

**Comment by EncryptSL** [comment]
I'm sorry I did not answer earlier, but my server provider did not answer my questions about setting up the database. Sorry for my english. ;) Ok i go this testing. ;).

**Comment by EncryptSL** [comment]
Working without error good job.

**Comment by PyvesB** [comment]
Awesome, let me know if anything unexpected happens in the coming days!

It would have been interesting to get the values of those parameters. Basically the plugin creates an initial connection to the database and uses it to interact with it later on. In your case MySQL closes the connection before the first player connection and the plugin has to open a new one. This is now handled in a cleaner and more reliable way. :-)
