### ISSUE TITLE
Mysql storage error

### ISSUE THREAD

**Issue by Xiazihong** [PyvesB/AdvancedAchievements#305]
Plug-in version: 5.6
Server Version: 1.7.10
Error log:
https://paste.ubuntu.com/26416109/
All Error log:
https://paste.ubuntu.com/26416114/

**Comment by R-Josef** [comment]
`[23:54:12 INFO]: [AdvancedAchievements] Player Fengshuai received the achievement: connect_1 (Good Choice)
[23:54:16 ERROR]: [AdvancedAchievements] Database write error while updating connection date and count:
java.sql.SQLException: Incorrect string value: '\xAC\xED\x00\x05sr...' for column 'playername' at row 1
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bdcc7c7]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bdcc7c7]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bdcc7c7]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bdcc7c7]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bdcc7c7]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bdcc7c7]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bdcc7c7]
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bdcc7c7]
        at com.hm 

.achievement.db.AbstractSQLDatabaseManager.lambda$null$11(AbstractSQLDatabaseManager.java:468) ~[?:?]
        at com.hm 

.achievement.db.SQLWriteOperation.attemptWrites(SQLWriteOperation.java:45) ~[?:?]
        at com.hm 

.achievement.db.SQLWriteOperation.lambda$executeOperation$0(SQLWriteOperation.java:33) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:54:16 ERROR]: [AdvancedAchievements] Database write error while registering an achievement:
java.sql.SQLException: Incorrect string value: '\xAC\xED\x00\x05sr...' for column 'playername' at row 1
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bdcc7c7]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bdcc7c7]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bdcc7c7]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bdcc7c7]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bdcc7c7]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bdcc7c7]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bdcc7c7]
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bdcc7c7]
        at com.hm 

.achievement.db.AbstractSQLDatabaseManager.lambda$registerAchievement$5(AbstractSQLDatabaseManager.java:319) ~[?:?]
        at com.hm 

.achievement.db.SQLWriteOperation.attemptWrites(SQLWriteOperation.java:45) ~[?:?]
        at com.hm 

.achievement.db.SQLWriteOperation.lambda$executeOperation$0(SQLWriteOperation.java:33) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
`
i have the same problem

**Comment by jiongjionger** [comment]
https://github.com/PyvesB/AdvancedAchievements/commit/e67f73068c71495b73be1d691d2e878439156304

This problem should be caused by
ps.setObject (1, uuid);

**Comment by PyvesB** [comment]
Hello guys,

I had tested quite extensively with SQLite, but there obviously is a problem with MySQL. Sorry about it, will release a fix in the coming days! 😉 

Cheers,

Pyves

**Comment by PyvesB** [comment]
This bug was introduced in #291 and should now be fixed. An official plugin update will be released shortly.
