### ISSUE TITLE
Could not pass event InventoryClickEvent to AdvancedAchievements v5.7.1

### ISSUE THREAD

**Issue by andris155** [PyvesB/AdvancedAchievements#336]
```
[17:08:01] [Server thread/INFO]: Neuromancer issued server command: /aach list
[17:08:15] [Server thread/ERROR]: Could not pass event InventoryClickEvent to AdvancedAchievements v5.7.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1349]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1349]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1349]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1349]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1981) ~[patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1349]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1349]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1349]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -50
	at java.util.ArrayList.elementData(ArrayList.java:422) ~[?:1.8.0_151]
	at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_151]
	at com.hm.achievement.gui.CategoryGUI.displayPage(CategoryGUI.java:199) ~[AdvancedAchievements%20(2).jar:?]
	at com.hm.achievement.gui.CategoryGUI.displayCategoryGUI(CategoryGUI.java:158) ~[AdvancedAchievements%20(2).jar:?]
	at com.hm.achievement.listener.ListGUIListener.onInventoryClick(ListGUIListener.java:81) ~[AdvancedAchievements%20(2).jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor351.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1349]
	... 16 more
```

**Comment by andris155** [comment]
I don't know how to reproduce. I find this error server log.

**Comment by PyvesB** [comment]
Your configuration file is not valid. Put a `{}` next to the `Commands` section and add it to the `DisabledCategories` list, that should do the trick!

**Comment by andris155** [comment]
Thanks!
