### ISSUE TITLE
Extend Kills category capabilities

### ISSUE THREAD

**Issue by eot13** [PyvesB/AdvancedAchievements#360]
Hello, could you add this category please:

- Mob with custom name killed (get the custom name)

**Comment by PyvesB** [comment]
Hello @eot13 !

Thanks for your suggestion, this seems reasonable. Hopefully we'll be able to just make some small changes to the _Kills_ category to add such support.

Anyone feel free to pick this up, otherwise I'll try to tackle it in the coming weeks. 😉 

Cheers,

Pyves

**Comment by eot13** [comment]
Thank you very much!

**Comment by JacekAA** [comment]
Hello Pyves!

This might not be the best place to post this, but as per your FAQ github is the best way to contact you, and my question is quite pertinent to this thread. If the Kill-type achievements are able to read an entities name, doesn't that mean that any sort of custom mob can be added to the Kill-type achievements? I'm fairly new to the whole plugin scene, so forgive me if I've missed a page that explains this exact thing. I'm curious about this because your FAQ says that you don't support MythicMobs, but if my MythicMob has a custom name (say, "&9Drowned Ghoul) can't I use the following achievement to track kills?
`&9Drowned_Ghoul:
    1:
      Message: "&8You killed a drowned ghoul!"
      Goal: "Land the killing blow on a Drowned Ghoul."
      DisplayName: Back to the Depths
      Name: kills_1_drownedghoul
`

**Comment by PyvesB** [comment]
@JacekAA yes, something like that would probably work. I just had no idea that these plugins were based on custom entity names, as people would just ask "add support for MythicMobs" without ever giving any details. 😉

**Comment by JacekAA** [comment]
Thank you for the reply! I'll be doing some testing towards the end of the week as to whether or not that's an option. The MythicMob has a 'Display' property in the config that floats a name above the mob (as in, Drowned Ghoul) but I'm not sure that this is the entity's actual name given that there is an actual 'Type' property that requires ENDER_DRAGON or WITHER_SKELETON or a similar vanilla MC entity name. Will keep you posted.

**Comment by JacekAA** [comment]
Sorry it took me so long to get back to you! It doesn't look like using the display name works. Adding functionality through the display name would be super awesome. Is there any more info I can give you to help with it?

**Comment by PyvesB** [comment]
@JacekAA Could you please give this custom version a try and tell me what messages are logged in the console when you kill a "Mythic" mob?

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/2136313/AdvancedAchievements.zip)

**Comment by JacekAA** [comment]
Here's the info I got from testing. I first tried adding two "entity kill" achievements, one of which used the MMob's display name (&2SkeletalKnight) and the other which used the MM name (SkeletalKnight). Here's the stacktrace for the error I got when doing that
`[15:58:09 ERROR]: Error occurred while enabling AdvancedAchievements v5.8.2 (Is it up to date?)
java.lang.NullPointerException: null
        at org.bukkit.configuration.file.YamlConfiguration.convertMapsToSections(YamlConfiguration.java:72) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at org.bukkit.configuration.file.YamlConfiguration.convertMapsToSections(YamlConfiguration.java:76) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:66) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:178) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:160) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:135) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at com.hm.achievement.module.DatabaseModule.provideSQLDatabaseManager(DatabaseModule.java:28) ~[?:?]
        at com.hm.achievement.module.DatabaseModule_ProvideSQLDatabaseManagerFactory.proxyProvideSQLDatabaseManager(DatabaseModule_ProvideSQLDatabaseManagerFactory.java:98) ~[?:?]
        at com.hm.achievement.module.DatabaseModule_ProvideSQLDatabaseManagerFactory.provideInstance(DatabaseModule_ProvideSQLDatabaseManagerFactory.java:65) ~[?:?]
        at com.hm.achievement.module.DatabaseModule_ProvideSQLDatabaseManagerFactory.get(DatabaseModule_ProvideSQLDatabaseManagerFactory.java:49) ~[?:?]
        at com.hm.achievement.module.DatabaseModule_ProvideSQLDatabaseManagerFactory.get(DatabaseModule_ProvideSQLDatabaseManagerFactory.java:14) ~[?:?]
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47) ~[?:?]
        at com.hm.achievement.db.CacheManager_Factory.provideInstance(CacheManager_Factory.java:32) ~[?:?]
        at com.hm.achievement.db.CacheManager_Factory.get(CacheManager_Factory.java:26) ~[?:?]
        at com.hm.achievement.db.CacheManager_Factory.get(CacheManager_Factory.java:8) ~[?:?]
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47) ~[?:?]
        at com.hm.achievement.listener.statistics.ConnectionsListener_Factory.provideInstance(ConnectionsListener_Factory.java:81) ~[?:?]
        at com.hm.achievement.listener.statistics.ConnectionsListener_Factory.get(ConnectionsListener_Factory.java:57) ~[?:?]
        at com.hm.achievement.listener.statistics.ConnectionsListener_Factory.get(ConnectionsListener_Factory.java:15) ~[?:?]
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47) ~[?:?]
        at com.hm.achievement.lifecycle.PluginLoader_Factory.provideInstance(PluginLoader_Factory.java:345) ~[?:?]
        at com.hm.achievement.lifecycle.PluginLoader_Factory.get(PluginLoader_Factory.java:248) ~[?:?]
        at com.hm.achievement.lifecycle.PluginLoader_Factory.get(PluginLoader_Factory.java:53) ~[?:?]
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47) ~[?:?]
        at com.hm.achievement.DaggerAdvancedAchievementsComponent.pluginLoader(DaggerAdvancedAchievementsComponent.java:1012) ~[?:?]
        at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:46) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]`

After removing the &2 achievement, the plugin loaded fine. I summoned a Skeletal Knight again, and killed it. This is what the console says:

`[16:03:42 INFO]: [AdvancedAchievements] JacekAA - custom name º2Skeletal Knight
[16:03:42 INFO]: [AdvancedAchievements] JacekAA - name º2Skeletal Knight`

I assume that's a fairly god sign? Let me know if there's more testing I can help out with

**Comment by PyvesB** [comment]
@JacekAA thank you for all the information! 

When specifying colours you need to add single quotes around the string, otherwise it will likely mess up with the YAML. This may have been the cause of the exception.

I have indeed not started the implementation, I only added a few log lines in that plugin version I shared. I'll keep you posted when I make some more progress.

**Comment by PyvesB** [comment]
@JacekAA I have drafted an implementation in #390 and have attached a test version, would you like to give it a try? Use `customname-...` as a subcategory value in the `Kills` category.

I would like to put a complete example in _config.yml_, do you have a good/fun custom mob name to suggest?

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/2190387/AdvancedAchievements.zip)

**Comment by JacekAA** [comment]
One of the default custom mobs provided by MythicMobs is one with the name &2Skeletal Knight, that would be a pretty good one to start with.
