### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Patbox** [PyvesB/AdvancedAchievements#377]
[15:34:29] [Server thread/ERROR]: Could not pass event PlayerBucketFillEvent to AdvancedAchievements v5.8.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[mc.jar:git-Paper-1437]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[mc.jar:git-Paper-1437]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[mc.jar:git-Paper-1437]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[mc.jar:git-Paper-1437]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[mc.jar:git-Paper-1437]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:187) ~[mc.jar:git-Paper-1437]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerBucketFillEvent(CraftEventFactory.java:164) ~[mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.ItemBucket.a(ItemBucket.java:44) ~[mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.ItemStack.a(ItemStack.java:316) ~[mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:405) ~[mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1044) ~[mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[mc.jar:git-Paper-1437]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [mc.jar:git-Paper-1437]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ArrayIndexOutOfBoundsException

**Comment by supertassu** [comment]
You've cut out the important part of the error. Please provide the full error.

**Comment by PyvesB** [comment]
@supertassu is right, we need the log lines after `Caused by: java.lang.ArrayIndexOutOfBoundsException`. 😉

**Comment by Patbox** [comment]
But after `Caused by: java.lang.ArrayIndexOutOfBoundsException` error ends. 

[00:19:00] [Server thread/INFO]: Usuni?to 0 podmiot?w.
[00:22:41] [Server thread/INFO]: protocolsupport.protocol.utils.authlib.GameProfile(uuid: null, name: FloRus, properties: {}) (/89.78.112.113:55605) lost connection: Disconnected
[00:27:04] [Server thread/ERROR]: Could not pass event PlayerBedEnterEvent to AdvancedAchievements v5.8.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[mc.jar:git-Paper-1437]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[mc.jar:git-Paper-1437]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[mc.jar:git-Paper-1437]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[mc.jar:git-Paper-1437]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.EntityHuman.a(EntityHuman.java:1256) ~[mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.EntityPlayer.a(EntityPlayer.java:685) ~[mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.BlockBed.interact(SourceFile:98) ~[mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:505) ~[mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:991) ~[mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[mc.jar:git-Paper-1437]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [mc.jar:git-Paper-1437]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [mc.jar:git-Paper-1437]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ArrayIndexOutOfBoundsException
[00:27:28] [Server thread/INFO]: Mi3lon has made the advancement [We Need to Go Deeper]
[00:33:24] [Server thread/INFO]: [PreciousStones] Mi3lon attempted to use a LEVER in zgredek124's Cuboid field [IRON_BLOCK|2292 64 -232]
[00:33:43] [Server thread/INFO]: [PreciousStones] Mi3lon attempted to use a WOOD_PLATE in zgredek124's Cuboid field [IRON_BLOCK|2292 64 -232]
[00:33:43] [Server thread/INFO]: [PreciousStones] Mi3lon attempted to use a WOOD_PLATE in zgredek124's Cuboid field [IRON_BLOCK|2292 64 -232]

**Comment by PyvesB** [comment]
I'm unsure where such an exception could be coming from. Does it happen on a regular basis, have you got a way to reproduce it easily?

**Comment by andris155** [comment]
```
[10:51:15] [Server thread/ERROR]: Could not pass event InventoryClickEvent to AdvancedAchievements v5.8.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1468]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.12.2.jar:git-Paper-1468]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1981) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1468]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1468]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -50
	at java.util.ArrayList.elementData(ArrayList.java:422) ~[?:1.8.0_171]
	at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_171]
	at com.hm.achievement.gui.CategoryGUI.displayPage(CategoryGUI.java:201) ~[AdvancedAchievements%20(2).jar:?]
	at com.hm.achievement.gui.CategoryGUI.displayCategoryGUI(CategoryGUI.java:158) ~[AdvancedAchievements%20(2).jar:?]
	at com.hm.achievement.listener.ListGUIListener.onInventoryClick(ListGUIListener.java:64) ~[AdvancedAchievements%20(2).jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor467.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1468]
	... 16 more
```

**Comment by PyvesB** [comment]
@andris155 I don't think this is related. Please open a separate issue and indicate how to reproduce the problem you're facing with any relevant configuration files. 😉

**Comment by Patbox** [comment]
I All I need to do is fill the bucket with water or use a bed

**Comment by PyvesB** [comment]
This is going to be a tough one to investigate! I've prepared a test version, could you please temporarily put it on your server, try filling a bucket and paste any log lines containing "Patbox"?

[AdvancedAchievements.zip](https://github.com/PyvesB/AdvancedAchievements/files/2172070/AdvancedAchievements.zip)

**Comment by Patbox** [comment]
`[16:05:02] [Server thread/INFO]: [AdvancedAchievements] Patbox - Event start
[16:05:02] [Server thread/INFO]: [AdvancedAchievements] Patbox - Finished pre-processing
[16:05:02] [Server thread/INFO]: [AdvancedAchievements] Patbox - Increase taken into account
[16:05:02] [Server thread/INFO]: [AdvancedAchievements] Patbox - Cooldown 1
[16:05:02] [Server thread/ERROR]: Could not pass event PlayerBucketFillEvent to AdvancedAchievements v5.8.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[Serwer.jar:git-Paper-1468]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[Serwer.jar:git-Paper-1468]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Serwer.jar:git-Paper-1468]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[Serwer.jar:git-Paper-1468]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[Serwer.jar:git-Paper-1468]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:187) ~[Serwer.jar:git-Paper-1468]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerBucketFillEvent(CraftEventFactory.java:164) ~[Serwer.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.ItemBucket.a(ItemBucket.java:44) ~[Serwer.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.ItemStack.a(ItemStack.java:316) ~[Serwer.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:405) ~[Serwer.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1044) ~[Serwer.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[Serwer.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[Serwer.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[Serwer.jar:git-Paper-1468]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Serwer.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [Serwer.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [Serwer.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [Serwer.jar:git-Paper-1468]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [Serwer.jar:git-Paper-1468]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(Unknown Source) ~[?:1.8.0_171]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_171]
	at com.hm.achievement.listener.statistics.AbstractRateLimitedListener.isInCooldownPeriod(AbstractRateLimitedListener.java:106) ~[?:?]
	at com.hm.achievement.listener.statistics.MilksLavaWaterBucketsListener.onPlayerBucketFill(MilksLavaWaterBucketsListener.java:73) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor142.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[Serwer.jar:git-Paper-1468]
	... 21 more
`

**Comment by PyvesB** [comment]
Okay, that's useful information! I think there is a problem with your _config.yml_ file could you please share it with me?

**Comment by Patbox** [comment]
#==============================O==============================#
# I---------------------------------------------------------I #
# |    Advanced Achievements 5.8.2 configuration - Readme   | #
# 1---------------------------------------------------------1 #
#==============================o==============================#
# You can use Minecraft chat colors in Message|DisplayName|Goal, but include double quotes around the whole text: "&4Color".
# Only spaces, NO tabs. Don't forget the indents (2 spaces per indentation level), plugin won't work otherwise!
# To check syntax errors in your file, use: yaml-online-parser.appspot.com
# Do NOT delete any top level (= not indentented) sections in the configuration file.
# Possible items for rewards/Crafts/Places/Breaks: hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# Possible mobs for the Kills section:    hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
# Default config.yml file:  github.com/PyvesB/AdvancedAchievements/blob/master/src/main/resources/config.yml
# Visit the wiki for some valuable additional documentation: github.com/PyvesB/AdvancedAchievements/wiki
#=============================O=O=============================#
# II-------------------------------------------------------II #
# |                    General  settings                    | #
# 2---------------------------------------------------------2 #
#=============================o=o=============================#
# Time in seconds between each /aach book (unless user has permission achievement.*).
TimeBook: 900

# Check for update on plugin launch and notify when an OP joins the game.
CheckForUpdate: true

# Set to true to activate firework effects when a player receives an achievement.
Firework: true

# Choose BALL_LARGE, BALL, BURST, CREEPER, STAR or RANDOM.
FireworkStyle: BALL_LARGE

# Set to true to activate simpler effects and a calm sound when a player receives an achievement.
# Ignored if Firework setting is set to true.
SimplifiedReception: false

# Number of players displayed in /aach top, week and month commands.
TopList: 5

# Set to true to activate particle effects when performing /aach book, /aach stats with all achievements and
# /aach top, week or month when ranked in the top list.
AdditionalEffects: true

# Set to true to activate sounds when performing /aach book, /aach stats with all achievements and
# /aach top, week or month when ranked in the top list.
Sound: true

# Set the icon of the plugin (default: shamrock, \u2618).
Icon: \u2618

# Set the color of the plugin (default: 5, dark purple).
Color: 5

# Notify other connected players when an achievement is received.
# Default behaviour, a player can override what he sees by using /aach toggle.
NotifyOtherPlayers: false

# When NotifyOtherPlayers is enabled, notifications are done using action bars when ActionBarNotify is true.
# When ActionBarNotify is false, chat messages are used.
ActionBarNotify: true

# Display achievement Name and Message as screen titles. No effect if using Minecraft 1.7.9 or 1.7.10.
TitleScreen: true

# When a player receives an achievement, the Name, Message and rewards of the achievement are displayed in
# the chat. If HoverableReceiverChatText is true, a single hoverable text will be displayed to the receiver.
# Otherwise texts will be displayed one after the other.
HoverableReceiverChatText: false

# Separator between name, description and date on a book page.
BookSeparator: ''

# Set the format of the achievement name in /aach list (default: "%ICON% %NAME% %ICON%").
ListAchievementFormat: '%ICON% %NAME% %ICON%'

# Set the format of the header used for most chat messages (default: "&7[%ICON%&7]").
ChatHeader: '&7[%ICON%&7]'

# Stop all stats from increasing when player in creative mode, including PlayedTime.
# Connection achievements will only be handled once a player switches to a non-creative mode.
RestrictCreative: false

# Stop all stats from increasing when player in spectator mode, including PlayedTime.
# Connection achievements will only be handled once a player switches to a non-spectator mode.
# No effect if using Minecraft 1.7.9 or 1.7.10.
RestrictSpectator: true

# Stop all stats from increasing when player in adventure mode, including PlayedTime.
# Connection achievements will only be handled once a player switches to a non-adventure mode.
RestrictAdventure: false

# Stop all stats from increasing when player in a specific world, including PlayedTime (delete the [] before adding values).
# Connection achievements will only be handled once a player enters a non-excluded world.
ExcludedWorlds: []

#  - yourWorld1
#  - yourWorld2
# Ignore vertical dimension (Y axis) when calculating distance statistics.
IgnoreVerticalDistance: false

# Don't show these categories in the achievement GUI or in the stats output (delete the [] before adding values).
# Also prevent obtaining achievements for these categories and prevent stats from increasing.
#  - PetMasterGive
#  - PetMasterReceive
#  - DistanceLlama
#  - DistanceGliding
# Obfuscate achievements that have not yet been received in /aach list.
ObfuscateNotReceived: false

# For categories with a series of related achievements where the only thing changing is the number of times
# the event has occurred, show achievements that have been obtained and show the next obtainable achievement,
# but obfuscate the additional achievements. For example, under Places, stone, the first achievement could have a
# target of 100 stone, the second 500 stone, and the third 1000 stone.  When ObfuscateProgressiveAchievements
# is true, initially only the 100 stone achievement will be readable in the GUI.  Once 100 stone have been placed,
# the 500 stone achievement will become legible.
ObfuscateProgressiveAchievements: false

# Hide categories with no achievements yet received in /aach list by marking them as locked.
HideNotReceivedCategories: false

# Completely hide categories for which the player does not have the corresponding count permissions.
HideNoPermissionCategories: false

# Hide the reward display in /aach list.
HideRewardDisplayInList: false

# Display precise statistic information in the /aach list progress bars.
EnrichedListProgressBars: true

# Annotate each achievement displayed in a /aach list category with a number.
NumberedItemsInList: false

# Color used for Goals and progress bars in /aach list when an achievement is not yet received.
ListColorNotReceived: 8

# Sort pages of the book in chronological order (false for reverse chronological order).
BookChronologicalOrder: true

# Do not take into account items broken with Silk Touch for the Breaks achievements.
DisableSilkTouchBreaks: false

# Do not take into account ores broken with Silk Touch for the Breaks achievements.
# DisableSilkTouchBreaks takes precedence over this. Not applicable to iron or gold ores.
DisableSilkTouchOreBreaks: false

# Name of the language file.
LanguageFileName: lang.yml

# Time in seconds between each statistic count. Only the listed categories are currently supported.
StatisticCooldown:
  LavaBuckets: 10
  WaterBuckets: 10
  Milk: 10
  Beds: 30
  Brewing: 5
  MusicDiscs: 30

# Display action bar message when player performs an action while in the cooldown period.
# No effect if using Minecraft 1.7.9 or 1.7.10.
CooldownActionBar: true

# Locale used to format dates in /aach book and /aach list. You must select an ISO 639 language code.
# The list of possible language codes can be found at www.loc.gov/standards/iso639-2/php/code_list.php
DateLocale: pl

# Display time of reception of achievements in /aach book and /aach list in addition to the date. For achievements
# received in plugin versions prior to 3.0, the precise time information is not available and will be displayed as midnight.
DateDisplayTime: true

# Register advancements with a description corresponding to the Goal parameter of each achievement.
# If changed, run /aach generate to regenerate advancements with the new parameter value taken into account.
# No effect if using Minecraft versions prior to 1.12.
RegisterAdvancementDescriptions: true

# If true, hide advancements from the advancement GUI. Advancement notifications will still appear when receiving achievements.
# No effect if using Minecraft versions prior to 1.12.
HideAdvancements: false

# If true, PlayedTime will no longer increase when the player is AFK. Requires Essentials to work.
IgnoreAFKPlayedTime: false

# Awarded when a player has received all the achievements. Use the same reward pattern as with achievements.
# See https://github.com/PyvesB/AdvancedAchievements/wiki/Rewards
AllAchievementsReceivedRewards:
  IncreaseMaxOxygen: 30
  Experience: 100

#=============================OOO=============================#
# III-----------------------------------------------------III #
# |                    Database settings                    | #
# 3---------------------------------------------------------3 #
#=============================ooo=============================#
# Make a daily backup of your local database (if sqlite).
DatabaseBackup: true

# Database type, sqlite, postgresql or mysql. Do a full server restart for this to take effect.
DatabaseType: sqlite

# Prefix added to the tables in the database. If you switch from the default tables names (no prefix),
# the plugin will attempt an automatic renaming. Otherwise you have to rename your tables manually.
# Do a full server restart for this to take effect.
TablePrefix: ''

# Specify additional options when opening a connection to a MySQL/PostgreSQL database. Start each option with &,
# for instance "&useUnicode=yes&characterEncoding=UTF-8". Make sure the key-value pairs themselves are URL encoded.
AdditionalConnectionOptions: ''

# Settings to link with MySQL database (ignored if sqlite or postgresql).
MYSQL:
  Database: jdbc:mysql://localhost:3306/minecraft
  User: root
  Password: root

# Settings to link with PostgresSQL database (ignored if sqlite or mysql).
# Refer to https://github.com/PyvesB/AdvancedAchievements/wiki/Installation to set up PostgreSQL.
POSTGRESQL:
  Database: jdbc:postgresql://localhost:5432/minecraft
  User: root
  Password: root

#============================OO=OO============================#
# IV-------------------------------------------------------IV #
# |                  Performance settings                   | #
# 4---------------------------------------------------------4 #
#============================oo=oo============================#
# DO NOT CHANGE THE FOLLOWING UNLESS YOU ARE AN EXPERIENCED USER. The intervals are in seconds. 
# Frequency of play time checks for players. Smaller values give more precision but more CPU usage.
PlaytimeTaskInterval: 60

# Calculates distance traveled by players. Smaller values give more precision but more CPU usage.
DistanceTaskInterval: 5

# Frequency of some statistics writes to the database. Do a full server restart, and not just /aach reload.
PooledRequestsTaskInterval: 10

#============================OOOOO============================#
# V---------------------------------------------------------V #
# |              Multiple action achievements               | #
# |       These require sub-categories and thresholds       | #
# 5---------------------------------------------------------5 #
#============================ooooo============================#
# When a specific block is placed (specify material name, lower case).
Places:
  stone:
    '1000':
      Message: '&4Postaw 1000 bloków kamienia'
      Name: stone_king
      DisplayName: Kamienny król
      Reward:
        Money: 100

# When a specific block is broken (specify material name, lower case).
# Below, the notation sand:1 means sand item with metadata 1 (red sand).
# When a specific mob is killed.
# Use an Entity name or poweredcreeper, in lower case.
# Use player to track player kills as a whole.
# Use specificplayer- followed by player UUID to track how many times a specific player has been killed.
# When a specific item is crafted (specify material name, lower case).
Crafts:
  crafting_table:
    '10':
      Message: Stwórz 10 crafting table
      Name: craft_1_blade
      DisplayName: Crafter
      Reward:
        Money: 10

# When a player enters a specific command (specify command prefixes in lower case without initial slash).
# For instance a command /awf add world from the AntiWorldFly plugin matches with subcategory 'awf add'.
# Aliases of a given command will also be taken into account.
# When animals breed (specify an entity name, lower case).
#===========================OOO=OOO===========================#
# VI-------------------------------------------------------VI #
# |               Normal action achievements                | #
# |          These are simply based on thresholds           | #
# 6---------------------------------------------------------6 #
#===========================ooo=ooo===========================#
# When a player connects during the day; statistic increases at most once per day.
Connections:
  '1':
    Message: Dołączyłeś na nasz serwer
    Name: connect_1
    DisplayName: Fajnie, że jesteś

# When the player dies.
Deaths:
  '1':
    Message: Umarłeś 1 raz
    Name: deaths_1
    DisplayName: Śmiertelny

# When an arrow is shot.
#===========================OOOOOOO===========================#
# VII-----------------------------------------------------VII #
# |               Command-based achievements                | #
# 7---------------------------------------------------------7 #
#===========================ooooooo===========================#
# Let achievement commands be given several times.
MultiCommand: true

# A player with achievement.give (or the console) can use /aach give yourAch1 PLAYER to give
# yourAch1 achievement to PLAYER. The /aach give command does NOT work with other achievements.
# When the command /aach add is called for this category.
#==========================OOOO=OOOO==========================#
# VIII---------------------------------------------------VIII #
# |  Parameters in future plugin versions will appear here  | #
# 8---------------------------------------------------------8 #
#==========================oooo=oooo==========================#
#When an arrow is shot.
Arrows: {}

#When a snowball is thrown.
Snowballs: {}

#When an egg is thrown.
Eggs: {}

#When a fish is caught.
Fish: {}

#When a treasure is caught with a fishing rod.
Treasures: {}

#When a tool/armor/weapon is broken.
ItemBreaks: {}

#When an item is eaten (excludes potions and milk).
EatenItems: {}

#When a sheep is sheared.
Shear: {}

#When a cow is milked.
Milk: {}

#When a bucket is filled with lava.
LavaBuckets: {}

#When a bucket is filled with water.
WaterBuckets: {}

#When a trade with a villager is made.
Trades: {}

#When an anvil is used.
AnvilsUsed: {}

#When an enchantment is performed.
Enchantments: {}

#When a bed is entered.
Beds: {}

#Maximum level reached.
MaxLevel: {}

#When a potion is consumed.
ConsumedPotions: {}

#Amount of time played on the server (in hours, use integers).
PlayedTime: {}

#When an item is dropped on the ground.
ItemDrops: {}

#When an item is picked up from the ground.
ItemPickups:
  nether_star:
    '1':
      Message: Zdobądź gwiazdę netherową
      Name: netherstar1
      DisplayName: Gwiazdka z nieba
      Reward:
        Money: 80

#When soil is plowed with a hoe.
HoePlowings: {}

#When bone meal is used to fertilise plants.
Fertilising: {}

#When an animal is tamed.
Taming: {}

#When a potion is brewed.
Brewing: {}

#When a firework is launched.
Fireworks: {}

#When a music disc is played.
MusicDiscs: {}

#When a player teleports with an enderpearl.
EnderPearls: {}

#When a player gives a pet to another player (requires PetMaster plugin version 1.3 or above).
PetMasterGive: {}

#When a player receives a pet from another player (requires PetMaster plugin version 1.3 or above).
PetMasterReceive: {}

#When an item is smelt in a furnace.
Smelting: {}

#When a distance is traveled by foot.
DistanceFoot:
'5000':
    Message: Przejdź 5000 kratek.
    Name: foot5000
    DisplayName: Włuczykij
    Reward:
      Money: 80

#When a distance is traveled on a pig.
DistancePig: {}

#When a distance is traveled on a horse.
DistanceHorse: {}

#When a distance is traveled in a minecart.
DistanceMinecart:
  '5000':
    Message: Przejedź 5000 kratek wagonikiem
    Name: minecart5000
    DisplayName: Miła podróż
    Reward:
      Money: 100

#When a distance is traveled in a boat.
DistanceBoat: {}

#When a distance is traveled with elytra.
DistanceGliding: {}

#When a distance is traveled on a llama.
DistanceLlama: {}

#When a specific mob is killed (specify an entity name or poweredcreeper or player, lower case).
Kills:
  player:
    '1':
      Message: Zabij gracza
      Name: murder
      DisplayName: Morderca
    '10':
      Message: Zabij 10 graczy
      Name: murder
      DisplayName: Seryjny morderca

#When animals breed (specify an entity name, lower case).
Breeding: {}

#Don't show these categories in the achievement GUI or in the stats output (delete the [] before using).
#Also prevent obtaining achievements for these categories and prevent stats from increasing.
#If changed, do a full server reload, and not just /aach reload.
DisabledCategories:
- Breaks
- PlayerCommands
- Custom
- Commands

#When a specific block is broken (specify material name, lower case).
Breaks: {}

#When a player enters a specific command (specify command prefixes in lower case without spaces).
PlayerCommands: {}

#When the command /aach add is called for this category.
Custom: {}

#A player with achievement.give (or the console) can use /aach give yourAch1 PLAYER to give
#yourAch1 achievement to PLAYER. The /aach give command does NOT work with other achievements.
Commands: {}

**Comment by PyvesB** [comment]
You have several empty categories without any achievements, but you haven't added them to the `DisabledCategories` which is intended for this purpose. Fix that bit of the configuration, it will solve your problem. 😉
