### ISSUE TITLE
No title appeared when obtaining a "DistanceMinecart" achievement

### ISSUE THREAD

**Issue by Mario359** [PyvesB/AdvancedAchievements#414]
I finished an achievement "DistanceMinecart" and an error appeared
It doesn't do that for other achievements because they have a "Message:..." section.
I use Spigot 1.13
```
[Server thread/ERROR]: Could not pass event PlayerAdvancedAchievementEvent to AdvancedAchievements v5.9.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
	at com.hm.achievement.utils.StatisticIncreaseHandler.checkThresholdsAndAchievements(StatisticIncreaseHandler.java:95) ~[?:?]
	at com.hm.achievement.runnable.AchieveDistanceRunnable.updateDistance(AchieveDistanceRunnable.java:150) ~[?:?]
	at com.hm.achievement.runnable.AchieveDistanceRunnable.validateMovementAndUpdateDistance(AchieveDistanceRunnable.java:106) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) [?:1.8.0_171]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) [?:1.8.0_171]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) [?:1.8.0_171]
	at com.hm.achievement.runnable.AchieveDistanceRunnable.run(AchieveDistanceRunnable.java:66) [AdvancedAchievements.jar:?]
	at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) [spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
	at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:877) [spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324) ~[spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
	at com.hm.achievement.listener.PlayerAdvancedAchievementListener.displayAchievement(PlayerAdvancedAchievementListener.java:351) ~[?:?]
	at com.hm.achievement.listener.PlayerAdvancedAchievementListener.onPlayerAdvancedAchievementReception(PlayerAdvancedAchievementListener.java:175) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-2b0e71c-7c341e9]
	... 17 more
```

The achievement:
```
DistanceMinecart:
  '20':
    Goal: Parcourir 20 mètres en wagonnet
    DisplayName: Essai de l'attraction
    Name: crea_minecart_20
    Reward:
      Money: 5
```

**Comment by PyvesB** [comment]
Hello @Mario359 ,

As specified in the [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki/FAQ-(Frequently-Asked-Questions)), the `Message` parameter is compulsory. 😉 

Cheers,

Pyves

**Comment by Mario359** [comment]
Oh, I hadn't seen it, thank you

**Comment by PyvesB** [comment]
You're welcome. 😉
