### ISSUE TITLE
Error ClassNotFoundException: net.milkbowl.vault.item.Items

### ISSUE THREAD

**Issue by WindUnwaken** [PyvesB/AdvancedAchievements#430]
after trying /aach generate
`chievementListener.java:202) ~[?:?]
        at com.hm.achievement.listener.PlayerAdvancedAchievementListener.onPlayerAdvancedAchievementReception(Playe
rAdvancedAchievementListener.java:172) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor254.execute(Unknown Source) ~
[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.1.jar:git-Paper-313]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.1.jar:git-Paper-3
13]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.1.jar:git-Pape
r-313]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.1.jar:git-P
aper-313]
        at com.hm.achievement.utils.StatisticIncreaseHandler.checkThresholdsAndAchievements(StatisticIncreaseHandle
r.java:95) ~[?:?]
        at com.hm.achievement.listener.statistics.AbstractListener.updateStatisticAndAwardAchievementsIfAvailable(A
bstractListener.java:46) ~[?:?]
        at com.hm.achievement.listener.statistics.PlowingFertilisingFireworksMusicDiscsListener.onPlayerInteract(Pl
owingFertilisingFireworksMusicDiscsListener.java:80) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor245.execute(Unknown Source) ~
[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.1.jar:git-Paper-313]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.1.jar:git-Paper-3
13]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.1.jar:git-Pape
r-313]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.1.jar:git-P
aper-313]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:2
55) ~[patched_1.13.1.jar:git-Paper-313]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:459) ~[patched_1.13.1.j
ar:git-Paper-313]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1334) ~[patched_1.13.1.jar:git-Pa
per-313]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.1.jar:gi
t-Paper-313]
        at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.1.jar:git
-Paper-313]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java
:12) ~[patched_1.13.1.jar:git-Paper-313]`
`        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) ~[patched_1.13.1.jar:git-Paper-313]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.1.jar:git-Pape
r-313]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper
-313]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper
-313]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Pap
er-313]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.item.Items
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.13.1.jar:git-
Paper-313]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.13.1.jar:git-
Paper-313]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
        ... 31 more`

**Comment by PyvesB** [comment]
Hello @WindUnwaken,

The latest released version of Advanced Achievements are not compatible with Vault 1.7.1. You can either:
* wait for a bit, the next Advanced Achievements release will hopefully come in the coming week.
* recompile Advanced Achievements from source as the issue has already been fixed in commit 32a794bae33e121d612809424c5dce8c63a57b0b.
* revert to the previous version of Vault for now.

Cheers, 

Pyves
