### ISSUE TITLE
NullPointerException: null - CommentedYamlConfiguration.getShallowKeys

### ISSUE THREAD

**Issue by mibby** [PyvesB/AdvancedAchievements#435]
Paper dev 319 (Spigot 1.13.1)
Compiled as of commit https://github.com/PyvesB/AdvancedAchievements/commit/1f2c355a6b6adc96519e3a7d235a09c65b1d485f

```
[18:16:47] [Server thread/INFO]: [AdvancedAchievements] Enabling AdvancedAchievements v5.9.3
[18:16:47] [Server thread/INFO]: [AdvancedAchievements] Loading and backing up configuration files...
[18:16:47] [Server thread/ERROR]: Error occurred while enabling AdvancedAchievements v5.9.3 (Is it up to date?)
java.lang.NullPointerException: null
	at com.hm.achievement.file.CommentedYamlConfiguration.getShallowKeys(CommentedYamlConfiguration.java:64) ~[?:?]
	at com.hm.achievement.config.ConfigurationParser.parseEnabledCategoriesWithSubcategories(ConfigurationParser.java:213) ~[?:?]
	at com.hm.achievement.config.ConfigurationParser.loadAndParseConfiguration(ConfigurationParser.java:84) ~[?:?]
	at com.hm.achievement.lifecycle.PluginLoader.loadAdvancedAchievements(PluginLoader.java:217) ~[?:?]
	at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:50) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.13.1.jar:git-Paper-319]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.1.jar:git-Paper-319]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.1.jar:git-Paper-319]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:438) ~[patched_1.13.1.jar:git-Paper-319]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:352) ~[patched_1.13.1.jar:git-Paper-319]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.1.jar:git-Paper-319]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.1.jar:git-Paper-319]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.1.jar:git-Paper-319]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:311) ~[patched_1.13.1.jar:git-Paper-319]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.1.jar:git-Paper-319]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[18:16:47] [Server thread/INFO]: [AdvancedAchievements] Disabling AdvancedAchievements v5.9.3
[18:16:47] [Server thread/INFO]: [AdvancedAchievements] Remaining requests sent to the database, plugin successfully disabled.
```

**Comment by mibby** [comment]
Broke due to this commit perhaps?
https://github.com/PyvesB/AdvancedAchievements/commit/61d27fd5d7294459c180a5f6bc325992a5c6bd50

**Comment by PyvesB** [comment]
Hello @mibby,

Thank you for reporting this, I think I know where the problem is coming from and will attempt to fix it in the evening. Stay tuned! 😉 

Cheers,

Pyves

**Comment by PyvesB** [comment]
@mibby actually I am unable to reproduce this issue. Could you please share your configuration file?

**Comment by PyvesB** [comment]
Okay, after some trial and error I believe I managed to fix the issue. Please rebuild from current master and let me know whether you encounter any other problems.
