### ISSUE TITLE
BatchUpdateException: Data truncation: Data too long for column 'blockid' at row 1

### ISSUE THREAD

**Issue by mibby** [PyvesB/AdvancedAchievements#450]
Compiled as of commit https://github.com/PyvesB/AdvancedAchievements/commit/74a985929ceab1413c43e8117bcad22284919928

```
[22:17:00] [Craft Scheduler Thread - 226/ERROR]: [AdvancedAchievements] Database write error while batching statistic updates:
java.sql.BatchUpdateException: Data truncation: Data too long for column 'blockid' at row 1
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.13.1.jar:git-Paper-368]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[patched_1.13.1.jar:git-Paper-368]
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163) ~[patched_1.13.1.jar:git-Paper-368]
	at com.mysql.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:1060) ~[patched_1.13.1.jar:git-Paper-368]
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970) ~[patched_1.13.1.jar:git-Paper-368]
	at com.hm.achievement.db.AsyncCachedRequestsSender.lambda$sendBatchedRequests$0(AsyncCachedRequestsSender.java:78) ~[?:?]
	at com.hm.achievement.db.SQLWriteOperation.attemptWrites(SQLWriteOperation.java:45) ~[?:?]
	at com.hm.achievement.db.AsyncCachedRequestsSender.sendBatchedRequests(AsyncCachedRequestsSender.java:83) ~[?:?]
	at com.hm.achievement.db.AsyncCachedRequestsSender.run(AsyncCachedRequestsSender.java:51) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.1.jar:git-Paper-368]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.1.jar:git-Paper-368]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.1.jar:git-Paper-368]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'blockid' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3974) ~[patched_1.13.1.jar:git-Paper-368]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912) ~[patched_1.13.1.jar:git-Paper-368]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[patched_1.13.1.jar:git-Paper-368]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[patched_1.13.1.jar:git-Paper-368]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2482) ~[patched_1.13.1.jar:git-Paper-368]
	at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1552) ~[patched_1.13.1.jar:git-Paper-368]
	at com.mysql.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:1034) ~[patched_1.13.1.jar:git-Paper-368]
	... 11 more

```

**Comment by PyvesB** [comment]
Hello @mibby,

Do you happen to have a group of subcategory types that is larger than 128 characters in _config.yml_?

Cheers,

Pyves

**Comment by mibby** [comment]
Hi @PyvesB,

The only category I can think of is one for tracking all bed placement.

```
  black_bed|blue_bed|brown_bed|cyan_bed|gray_bed|green_bed|light_blue_bed|light_gray_bed|lime_bed|magenta_bed|orange_bed|pink_bed|purple_bed|red_bed|white_bed|yellow_bed:
    '5':
      Goal: Place 5 beds.
      Message: '&4You have placed 5 beds!'
      Name: place_5_beds
      DisplayName: No Place Like Home
    '10':
      Goal: Place 10 beds.
      Message: '&4You have placed 10 beds!'
      Name: place_10_beds
      DisplayName: Home For The Whole Family
    '22':
      Goal: Place 22 beds.
      Message: '&4You have placed 22 beds!'
      Name: place_22_beds
      DisplayName: Monopoly
```

**Comment by PyvesB** [comment]
Yes, that's the problem, only up to 128 characters are supported for MySQL and PostgreSQL, but there is virtually no limit for SQLite. I might bump up the limit again, though it's hard to know when to stop... 😄

**Comment by mibby** [comment]
How else would I track every single new bed type in 1.13 without the limit being increased for MySQL?

**Comment by PyvesB** [comment]
Currently there isn't any other way to do this with the plugin in Minecraft 1.13.

**Comment by mibby** [comment]
I'll remove some beds from the config until then. :(

**Comment by PyvesB** [comment]
If you're comfortable with Git, you can also change the `128` occurrences in [this method](https://github.com/PyvesB/AdvancedAchievements/blob/6fb79f0c113f47c2df0034cab81ea7f830486beb/advanced-achievements-plugin/src/main/java/com/hm/achievement/db/DatabaseUpdater.java#L318) to a larger number in the meantime.

**Comment by PyvesB** [comment]
I have extended the length to 192 on the master branch. Hopefully this will be enough for most use cases. 😉
