### ISSUE TITLE
MySQLSyntaxErrorException on table initialization

### ISSUE THREAD

**Issue by sgdc3** [PyvesB/AdvancedAchievements#471]
```
[00:03:45] [Server thread/ERROR]: [AdvancedAchievements] A non recoverable error was encountered while loading the plugin, disabling it:
com.hm.achievement.exception.PluginLoadError: Error while initialising database tables.
	at com.hm.achievement.db.DatabaseUpdater.initialiseTables(DatabaseUpdater.java:127) ~[?:?]
	at com.hm.achievement.db.AbstractDatabaseManager.initialise(AbstractDatabaseManager.java:110) ~[?:?]
	at com.hm.achievement.lifecycle.PluginLoader.loadAdvancedAchievements(PluginLoader.java:220) ~[?:?]
	at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:50) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1594]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1594]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1594]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1594]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1594]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1594]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1594]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1594]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1594]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1594]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.sql.BatchUpdateException: Specified key was too long; max key length is 767 bytes
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_171]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_171]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.12.2.jar:git-Paper-1594]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[patched_1.12.2.jar:git-Paper-1594]
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163) ~[patched_1.12.2.jar:git-Paper-1594]
	at com.mysql.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:1060) ~[patched_1.12.2.jar:git-Paper-1594]
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970) ~[patched_1.12.2.jar:git-Paper-1594]
	at com.hm.achievement.db.DatabaseUpdater.initialiseTables(DatabaseUpdater.java:125) ~[?:?]
	... 14 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_171]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_171]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.12.2.jar:git-Paper-1594]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[patched_1.12.2.jar:git-Paper-1594]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[patched_1.12.2.jar:git-Paper-1594]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973) ~[patched_1.12.2.jar:git-Paper-1594]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[patched_1.12.2.jar:git-Paper-1594]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[patched_1.12.2.jar:git-Paper-1594]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[patched_1.12.2.jar:git-Paper-1594]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480) ~[patched_1.12.2.jar:git-Paper-1594]
	at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1552) ~[patched_1.12.2.jar:git-Paper-1594]
	at com.mysql.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:1034) ~[patched_1.12.2.jar:git-Paper-1594]
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970) ~[patched_1.12.2.jar:git-Paper-1594]
	at com.hm.achievement.db.DatabaseUpdater.initialiseTables(DatabaseUpdater.java:125) ~[?:?]
	... 14 more
```

**Comment by sgdc3** [comment]
Using MariaDB as database

**Comment by PyvesB** [comment]
Hello @sgdc3,

Advanced Achievements does not officially support MariaDB, I would recommend switching to one of the several other database types supported, SQLite, H2, PostgreSQL or MySQL. Alternatively, I'm guessing that your `TablePrefix` is very long, or that the configured page size of the database is too small. 😉 

Cheers,

Pyves

**Comment by sgdc3** [comment]
@PyvesB I'm not using the table prefix, this is the log of the queries sent by the plugin:

```MYSQL
181215 15:07:38	 1865 Query	START TRANSACTION
		 1865 Query	COMMIT
		 1865 Query	START TRANSACTION
		 1865 Query	COMMIT
		 1867 Connect	root@localhost as anonymous on skyblock3_achievements
		 1867 Query	/* mysql-connector-java-5.1.45 ( Revision: 9131eefa398531c7dc98776e8a3fe839e544c5b2 ) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS tx_isolation, @@wait_timeout AS wait_timeout
		 1867 Query	SET NAMES utf8mb4
		 1867 Query	SET character_set_results = NULL
		 1867 Query	SET autocommit=1
		 1867 Query	SET sql_mode='NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES'
		 1867 Query	CREATE TABLE IF NOT EXISTS achievements (playername char(36),achievement varchar(64),description varchar(128),date TIMESTAMP,PRIMARY KEY (playername, achievement))
		 1867 Query	CREATE TABLE IF NOT EXISTS places (playername char(36),blockid varchar(192),places INT,PRIMARY KEY(playername, blockid))
		 1867 Query	CREATE TABLE IF NOT EXISTS breaks (playername char(36),blockid varchar(192),breaks INT,PRIMARY KEY(playername, blockid))
		 1867 Query	CREATE TABLE IF NOT EXISTS kills (playername char(36),mobname varchar(192),kills INT,PRIMARY KEY(playername, mobname))
		 1867 Query	CREATE TABLE IF NOT EXISTS crafts (playername char(36),item varchar(192),crafts INT,PRIMARY KEY(playername, item))
		 1867 Query	CREATE TABLE IF NOT EXISTS breeding (playername char(36),mobname varchar(192),breeding INT,PRIMARY KEY(playername, mobname))
		 1867 Query	CREATE TABLE IF NOT EXISTS playercommands (playername char(36),command varchar(192),playercommands INT,PRIMARY KEY(playername, command))
		 1867 Query	CREATE TABLE IF NOT EXISTS custom (playername char(36),customname varchar(192),custom INT,PRIMARY KEY(playername, customname))
		 1867 Query	CREATE TABLE IF NOT EXISTS connections (playername char(36),connections INT,date varchar(10),PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS deaths (playername char(36),deaths BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS arrows (playername char(36),arrows BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS snowballs (playername char(36),snowballs BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS eggs (playername char(36),eggs BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS fish (playername char(36),fish BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS treasures (playername char(36),treasures BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS itembreaks (playername char(36),itembreaks BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS eatenitems (playername char(36),eatenitems BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS shears (playername char(36),shears BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS milks (playername char(36),milks BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS lavabuckets (playername char(36),lavabuckets BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS waterbuckets (playername char(36),waterbuckets BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS trades (playername char(36),trades BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS anvils (playername char(36),anvils BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS enchantments (playername char(36),enchantments BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS beds (playername char(36),beds BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS levels (playername char(36),levels BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS consumedpotions (playername char(36),consumedpotions BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS playedtime (playername char(36),playedtime BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS drops (playername char(36),drops BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS pickups (playername char(36),pickups BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS hoeplowing (playername char(36),hoeplowing BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS fertilising (playername char(36),fertilising BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS tames (playername char(36),tames BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS brewing (playername char(36),brewing BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS fireworks (playername char(36),fireworks BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS musicdiscs (playername char(36),musicdiscs BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS enderpearls (playername char(36),enderpearls BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS petmastergive (playername char(36),petmastergive BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS petmasterreceive (playername char(36),petmasterreceive BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS smelting (playername char(36),smelting BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS distancefoot (playername char(36),distancefoot BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS distancepig (playername char(36),distancepig BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS distancehorse (playername char(36),distancehorse BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS distanceminecart (playername char(36),distanceminecart BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS distanceboat (playername char(36),distanceboat BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS distancegliding (playername char(36),distancegliding BIGINT,PRIMARY KEY (playername))
		 1867 Query	CREATE TABLE IF NOT EXISTS distancellama (playername char(36),distancellama BIGINT,PRIMARY KEY (playername))
		 1867 Quit	
		 1865 Query	START TRANSACTION
		 1865 Query	COMMIT
		 1865 Query	START TRANSACTION
		 1865 Query	COMMIT
```

**Comment by sgdc3** [comment]
Fixed by creating the database using latin1 encoding.

**Comment by PyvesB** [comment]
Quite strange. However, glad to hear that that solved your issue! ^^
