### ISSUE TITLE
Error, Porblem not working

### ISSUE THREAD

**Issue by qvisten1** [PyvesB/AdvancedAchievements#558]
![Screenshot_8](https://user-images.githubusercontent.com/20997276/61366422-d344d400-a889-11e9-8bbd-8d507230fa11.png)

**Comment by PyvesB** [comment]
Hello @qvisten1,

Please read the server's startup logs, they should indicate why the plugin has been disabled.

Cheers,

Pyves

**Comment by qvisten1** [comment]
[11:53:55] [Server thread/INFO]: [AdvancedAchievements] Enabling AdvancedAchievements v5.12.3
[11:53:55] [Server thread/INFO]: [AdvancedAchievements] Loading and backing up configuration files...
[11:53:55] [Server thread/WARN]: [AdvancedAchievements] Overriding configuration: disabling PetMasterGive and PetMasterReceive categories.
[11:53:55] [Server thread/WARN]: [AdvancedAchievements] Ensure you have placed Pet Master with a minimum version of 1.4 in your plugins folder or add PetMasterGive and PetMasterReceive to the DisabledCategories list in config.yml.
[11:53:55] [Server thread/ERROR]: [AdvancedAchievements] A non recoverable error was encountered while loading the plugin, disabling it:
com.hm.achievement.exception.PluginLoadError: Achievement with path (PlayerCommands.home.1) is missing its Message parameter in config.yml.
	at com.hm.achievement.config.ConfigurationParser.parseAchievement(ConfigurationParser.java:327) ~[?:?]
	at com.hm.achievement.config.ConfigurationParser.parseAchievements(ConfigurationParser.java:306) ~[?:?]
	at com.hm.achievement.config.ConfigurationParser.parseAchievements(ConfigurationParser.java:289) ~[?:?]
	at com.hm.achievement.config.ConfigurationParser.loadAndParseConfiguration(ConfigurationParser.java:89) ~[?:?]
	at com.hm.achievement.lifecycle.PluginLoader.loadAdvancedAchievements(PluginLoader.java:230) ~[?:?]
	at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:50) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.3.jar:git-Paper-124]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.3.jar:git-Paper-124]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419) ~[patched_1.14.3.jar:git-Paper-124]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.3.jar:git-Paper-124]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.3.jar:git-Paper-124]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464) ~[patched_1.14.3.jar:git-Paper-124]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282) ~[patched_1.14.3.jar:git-Paper-124]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:859) ~[patched_1.14.3.jar:git-Paper-124]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[11:53:55] [Server thread/INFO]: [AdvancedAchievements] Disabling AdvancedAchievements v5.12.3
[11:53:55] [Server thread/INFO]: [AdvancedAchievements] Remaining requests sent to the database, plugin successfully disabled.

**Comment by qvisten1** [comment]
https://pastebin.com/73ww6VpQ

**Comment by PyvesB** [comment]
There you are, you've got a clear answer from the logs:

> com.hm.achievement.exception.PluginLoadError: Achievement with path (PlayerCommands.home.1) is missing its Message parameter in config.yml

😉

**Comment by qvisten1** [comment]
'1':
      Goal: Went home for the first time.
      Name: playercmd_home_1
      DisplayName: New Home
      Rewards:
        Item: Cookie 1



What should i change? Sorry im not that good with plugin and such

**Comment by PyvesB** [comment]
Well, you're missing the `Message` parameter inside, simply add it. The default configuration has valid examples of this.
