### ISSUE TITLE
I get this issue but i am not experienced enough to fix it, any help?

### ISSUE THREAD

**Issue by Theminerkid99** [PyvesB/AdvancedAchievements#581]
> [17:03:08] [Server thread/INFO]: [AdvancedAchievements] Enabling AdvancedAchievements v5.12.4
[17:03:08] [Server thread/INFO]: [AdvancedAchievements] Loading and backing up configuration files...
[17:03:08] [Server thread/WARN]: [AdvancedAchievements] Overriding configuration: disabling PetMasterGive and PetMasterReceive categories.
[17:03:08] [Server thread/WARN]: [AdvancedAchievements] Ensure you have placed Pet Master with a minimum version of 1.4 in your plugins folder or add PetMasterGive and PetMasterReceive to the DisabledCategories list in config.yml.
[17:03:08] [Server thread/ERROR]: [AdvancedAchievements] A non recoverable error was encountered while loading the plugin, disabling it:
com.hm.achievement.exception.PluginLoadError: Achievement with path (Connections.1) is missing its Message parameter in config.yml.
        at com.hm.achievement.config.ConfigurationParser.parseAchievement(ConfigurationParser.java:327) ~[AdvancedAchievements.jar:?]
        at com.hm.achievement.config.ConfigurationParser.parseAchievements(ConfigurationParser.java:306) ~[AdvancedAchievements.jar:?]
        at com.hm.achievement.config.ConfigurationParser.parseAchievements(ConfigurationParser.java:276) ~[AdvancedAchievements.jar:?]
        at com.hm.achievement.config.ConfigurationParser.loadAndParseConfiguration(ConfigurationParser.java:89) ~[AdvancedAchievements.jar:?]
        at com.hm.achievement.lifecycle.PluginLoader.loadAdvancedAchievements(PluginLoader.java:230) ~[AdvancedAchievements.jar:?]
        at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:50) [AdvancedAchievements.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [spigot-1.14.4.jar:git-Spigot-94af569-5d335e9]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.4.jar:git-Spigot-94af569-5d335e9]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.14.4.jar:git-Spigot-94af569-5d335e9]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot-1.14.4.jar:git-Spigot-94af569-5d335e9]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot-1.14.4.jar:git-Spigot-94af569-5d335e9]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot-1.14.4.jar:git-Spigot-94af569-5d335e9]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot-1.14.4.jar:git-Spigot-94af569-5d335e9]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [spigot-1.14.4.jar:git-Spigot-94af569-5d335e9]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[17:03:08] [Server thread/INFO]: [AdvancedAchievements] Disabling AdvancedAchievements v5.12.4
[17:03:08] [Server thread/INFO]: [AdvancedAchievements] Remaining requests sent to the database, plugin successfully disabled.

**Comment by PyvesB** [comment]
Hello @Theminerkid99,

The plugin is guiding you on what's wrong:

> Achievement with path (Connections.1) is missing its Message parameter in config.yml

Cheers,

Pyves
