### ISSUE TITLE
Configuration syntax error

### ISSUE THREAD

**Issue by kacperleague9** [PyvesB/AdvancedAchievements#629]
[13:36:00] [Server thread/ERROR]: Cannot load plugins/AdvancedAchievements/config.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
 in 'string', line 288, column 7:
          Command
          ^
could not find expected ':'
 in 'string', line 289, column 16:
            Execute: "level add PLAYER xp 50"
                   ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:178) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:160) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:135) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at com.hm.achievement.module.ConfigModule.providesLangConfig(ConfigModule.java:71) [AdvancedAchievements%20(1).jar:?]
	at com.hm.achievement.module.ConfigModule_ProvidesLangConfigFactory.providesLangConfig(ConfigModule_ProvidesLangConfigFactory.java:41) [AdvancedAchievements%20(1).jar:?]
	at com.hm.achievement.module.ConfigModule_ProvidesLangConfigFactory.get(ConfigModule_ProvidesLangConfigFactory.java:31) [AdvancedAchievements%20(1).jar:?]
	at com.hm.achievement.module.ConfigModule_ProvidesLangConfigFactory.get(ConfigModule_ProvidesLangConfigFactory.java:1) [AdvancedAchievements%20(1).jar:?]
	at com.hm.dagger.internal.DoubleCheck.get(DoubleCheck.java:47) [AdvancedAchievements%20(1).jar:?]
	at com.hm.achievement.command.executable.HelpCommand_Factory.get(HelpCommand_Factory.java:41) [AdvancedAchievements%20(1).jar:?]
	at com.hm.achievement.command.executable.HelpCommand_Factory.get(HelpCommand_Factory.java:1) [AdvancedAchievements%20(1).jar:?]
	at com.hm.dagger.internal.DoubleCheck.get(DoubleCheck.java:47) [AdvancedAchievements%20(1).jar:?]
	at com.hm.dagger.internal.SetFactory.get(SetFactory.java:126) [AdvancedAchievements%20(1).jar:?]
	at com.hm.dagger.internal.SetFactory.get(SetFactory.java:37) [AdvancedAchievements%20(1).jar:?]
	at com.hm.dagger.internal.SetFactory.get(SetFactory.java:119) [AdvancedAchievements%20(1).jar:?]
	at com.hm.dagger.internal.SetFactory.get(SetFactory.java:37) [AdvancedAchievements%20(1).jar:?]
	at com.hm.dagger.internal.DelegateFactory.get(DelegateFactory.java:36) [AdvancedAchievements%20(1).jar:?]
	at com.hm.achievement.lifecycle.PluginLoader_Factory.get(PluginLoader_Factory.java:131) [AdvancedAchievements%20(1).jar:?]
	at com.hm.achievement.lifecycle.PluginLoader_Factory.get(PluginLoader_Factory.java:1) [AdvancedAchievements%20(1).jar:?]
	at com.hm.dagger.internal.DoubleCheck.get(DoubleCheck.java:47) [AdvancedAchievements%20(1).jar:?]
	at com.hm.dagger.internal.DelegateFactory.get(DelegateFactory.java:36) [AdvancedAchievements%20(1).jar:?]
	at com.hm.achievement.DaggerAdvancedAchievementsComponent.pluginLoader(DaggerAdvancedAchievementsComponent.java:573) [AdvancedAchievements%20(1).jar:?]
	at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:46) [AdvancedAchievements%20(1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning a simple key
 in 'string', line 288, column 7:

**Comment by supertassu** [comment]
Hi, looks like your config.yml has a syntax error. Could you share your configuration in a [code block](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks)?
