### ISSUE TITLE
InventoryClickEvent

### ISSUE THREAD

**Issue by AviRendall** [PyvesB/AdvancedAchievements#64]
```
[Server thread/ERROR]: Could not pass event InventoryClickEvent to AdvancedAchievements v3.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-c3e4052-1953f52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-c3e4052-1953f52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-c3e4052-1953f52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1853) [server.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [server.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [server.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-c3e4052-1953f52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_65]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_65]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [server.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [server.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [server.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [server.jar:git-Spigot-c3e4052-1953f52]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [server.jar:git-Spigot-c3e4052-1953f52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
Caused by: java.lang.IllegalArgumentException: text contains invalid characters
	at org.bukkit.map.MapFont.getWidth(MapFont.java:52) ~[server.jar:git-Spigot-c3e4052-1953f52]
	at com.hm.achievement.command.ListCommand.buildLoreString(ListCommand.java:819) ~[?:?]
	at com.hm.achievement.command.ListCommand.createGUIItem(ListCommand.java:775) ~[?:?]
	at com.hm.achievement.command.ListCommand.createCategoryGUIMultiple(ListCommand.java:699) ~[?:?]
	at com.hm.achievement.listener.ListGUIListener.onInventoryClick(ListGUIListener.java:66) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_65]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_65]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-c3e4052-1953f52]
	... 15 more
```

What's wrong?

**Comment by PyvesB** [comment]
Hello, 

Could you please share me your lang.yml file? 

Cheers, 

Pyves

**Comment by AviRendall** [comment]
```

# +--------------------------------------------------------+
# |           Advanced Achievements language file          |
# +--------------------------------------------------------+
configuration-successfully-reloaded: Achievements successfully reloaded.
configuration-reload-failed: Errors while reloading configuration. Please view logs for more details.
no-permissions: У Вас нет прав, чтобы сделать это.
top-achievement: 'Топ игроков по кол-ву достижений:'
player-rank: 'Текущее место в топе:'
number-achievements: 'Кол-во достежений:'
book-received: Получена книга достижений!
book-delay: You must wait TIME seconds between each book reception!
list-delay: You must wait TIME seconds between each list command!
book-name: ДОСТИЖЕНИЯ
player-offline: Игрок PLAYER находится вне сети!
achievement-already-received: Игрок PLAYER уже получил(-а) это достижение!
achievement-not-found: Сожалеем, но это достижение не найдено на просторах сервера...
achievement-given: Достижение присвоено!
achievement-received: 'PLAYER заслужил(-а) достижение:'
achievement-new: 'Получено новое достижение:'
check-achievement-true: PLAYER заслужил(-а) достижение ACH!
check-achievements-false: PLAYER еще не заслужил(-а) достижение ACH!
delete-achievements: Достижение ACH отобрано у игрока PLAYER.
item-reward-received: 'Получена награда за достижение:'
money-reward-received: 'Получена валюта: £AMOUNT !'
command-reward: Произведена выдача награды!
aach-command-book: Получить книгу достежений.
aach-command-stats: Количество полученных вами достижений.
aach-command-list: Посмотреть список достижений (в чате).
aach-command-top: Посмотреть топ игроков по кол-ву достежений.
aach-command-give: Присвоить достижение ACH игроку NAME.
aach-command-reload: Перезагрузить конфиг плагина.
aach-command-info: Посмотреть информацию о плагине.
aach-command-check: Проверить, получил(-а) ли игрок NAME достижение ACH.
aach-command-delete: Отобрать достижение ACH у игрока NAME.
version-command-name: 'Название:'
version-command-version: 'Версия:'
version-command-website: 'Сайт:'
version-command-author: 'Разработчик:'
version-command-description: 'Описание:'
version-command-description-details: Плагин позволяет вводить свои достижения на сервер.
version-command-vault: 'Интеграция с Vault:'
version-command-database: 'Тип базы данных:'
list-gui-title: '&5&lСписок достижений'
list-reward: ';&fНаграда: '
list-reward-money: ' &6Деньги'
list-reward-item: '&7Предмет(ы)'
list-reward-command: '&9Титул'
list-amount: '; Кол-во: '
list-connections: Входы на сервер
list-places: Поставленные блоки
list-breaks: Поломанные блоки
list-kills: Убийства
list-crafts: Созданные предметы
list-deaths: Смерти
list-arrows: Произведенные выстрелы
list-snowballs: Брошенные снежки
list-eggs: Разбитые яйца
list-fish: Рыбная ловля
list-itembreaks: Сломанные предметы
list-eatenitems: Употребленная пища
list-shear: Подстриженные овцы
list-milk: Подоенные коровы
list-trades: Торговля
list-anvils: Кузнечное дело
list-enchantments: Наложение чар
list-beds: Заправленные кровати
list-maxlevel: Уровень персонажа
list-potions: Алкоголизм
list-distance-foot: Пройденные на своих двух километры
list-distance-pig: Пройденные верхом на свинье километры
list-distance-horse: Пройденные верхом на лошади километры
list-distance-minecart: Пройденные в вагонетке километры
list-distance-boat: Пройденные на лодке мили
list-itemdrops: Выброшенные предметы
list-hoeplowings: Фермерство
list-fertilising: Садоводство
list-taming: Приручение животных
list-brewing: Пивоварение
list-fireworks: Запуски фейерверков
list-commands: Уникальные достижения
list-playedtime: Проведенное на сервере время
list-distance-gliding: Пройденное расстояние с использованием крыльев
list-musicdiscs: Прослушанные пластинки
list-enderpearls: Перемещения с использованием жемчужин Эндера
list-achievement-received: '&a✓&f '
list-achievement-not-received: '&4✗&8 '
book-date: Издание от DATE.
list-back-message: '&7Назад'
week-achievement: 'Топ недели:'
month-achievement: 'Топ месяца:'
aach-command-week: Показать топ недели.
aach-command-month: Показать топ месяца.
not-ranked: Вы еще не входите в топ этого периода.
aach-command-book-hover: В этой книжке собраны (ну, или будут собраны) достижения, полученные вами.
aach-command-stats-hover: Полоса прогресса. Заполни ее =)
aach-command-list-hover: Меню достижений с прогрессом и описанием каждого!
aach-command-top-hover: Кто заядлый охотник за достижениями?
aach-command-give-hover: Игрок должен быть онлайн, чтобы выдать ему достижение.
aach-command-reload-hover: Не хочешь перезагрузить конфиг плагина?.
aach-command-info-hover: Немного информации о плагине!
aach-command-check-hover: Не забудь про коды цветов, указанные в конфиге.
aach-command-delete-hover: Игрок должен быть онлайн, чтобы отобрать у него достижение.
aach-command-week-hover: Лучшие охотники за достижениями за неделю!
aach-command-month-hover: Лучшие охотники за достижениями за месяц!
aach-tip: '&8Вы можете &7&n&oнавести&r &8или &7&n&oкликнуть&r &8по одной из команд сверху!'

```

It's russian lang.

**Comment by PyvesB** [comment]
Okay, I see, I'm using a Bukkit method that apparently doesn't seem to support the cyrillic alphabet. I'll try to issue a fix as soon as possible. ;-)

**Comment by AviRendall** [comment]
Thanks :)

**Comment by PyvesB** [comment]
Done, the 3.0.1 version is on its way! ;-)
