### ISSUE TITLE
sql database not working

### ISSUE THREAD

**Issue by hammad-alhassan** [PyvesB/AdvancedAchievements#649]
hi i did everything

DatabaseAddress: "eu01-sql.pebblehost.com"
DatabaseUser: customer_99061_data
DatabasePassword: ********

when i enable the sql the plugin stops working this is the console and yes i have the latest version

```
[04:02:39] [Server thread/INFO]: [AdvancedAchievements] Enabling AdvancedAchievements v5.13.4

[04:02:40] [Server thread/INFO]: [AdvancedAchievements] Loading and backing up configuration files...
[04:02:40] [Server thread/WARN]: [AdvancedAchievements] Overriding configuration: disabling PetMasterGive and PetMasterReceive categories.
[04:02:40] [Server thread/WARN]: [AdvancedAchievements] Ensure you have placed Pet Master with a minimum version of 1.4 in your plugins folder or add PetMasterGive and PetMasterReceive to the DisabledCategories list in config.yml.
[04:02:40] [Server thread/INFO]: [AdvancedAchievements] Loaded 57 achievements in 48 categories.
[04:02:40] [Server thread/INFO]: [AdvancedAchievements] 2 disabled categories: [PetMasterReceive, PetMasterGive]
[04:02:40] [Server thread/INFO]: [AdvancedAchievements] Registering event listeners...
[04:02:40] [Server thread/INFO]: [AdvancedAchievements] Initialising database...
[04:02:40] [Server thread/ERROR]: [AdvancedAchievements] A non recoverable error was encountered while loading the plugin, disabling it:
com.hm.achievement.exception.PluginLoadError: Error while initialising database tables.
	at com.hm.achievement.db.DatabaseUpdater.initialiseTables(DatabaseUpdater.java:127) ~[?:?]
	at com.hm.achievement.db.AbstractDatabaseManager.initialise(AbstractDatabaseManager.java:110) ~[?:?]
	at com.hm.achievement.lifecycle.PluginLoader.loadAdvancedAchievements(PluginLoader.java:141) ~[?:?]
	at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:50) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-239]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-239]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-239]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-239]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-239]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-239]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-239]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-239]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.sql.BatchUpdateException: No database selected
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_222]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_222]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.14.4.jar:git-Paper-239]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[patched_1.14.4.jar:git-Paper-239]
	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163) ~[patched_1.14.4.jar:git-Paper-239]
	at com.mysql.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:1060) ~[patched_1.14.4.jar:git-Paper-239]
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970) ~[patched_1.14.4.jar:git-Paper-239]
	at com.hm.achievement.db.DatabaseUpdater.initialiseTables(DatabaseUpdater.java:125) ~[?:?]
	... 12 more
Caused by: java.sql.SQLException: No database selected
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[patched_1.14.4.jar:git-Paper-239]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[patched_1.14.4.jar:git-Paper-239]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[patched_1.14.4.jar:git-Paper-239]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[patched_1.14.4.jar:git-Paper-239]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[patched_1.14.4.jar:git-Paper-239]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491) ~[patched_1.14.4.jar:git-Paper-239]
	at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1552) ~[patched_1.14.4.jar:git-Paper-239]
	at com.mysql.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:1034) ~[patched_1.14.4.jar:git-Paper-239]
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970) ~[patched_1.14.4.jar:git-Paper-239]
	at com.hm.achievement.db.DatabaseUpdater.initialiseTables(DatabaseUpdater.java:125) ~[?:?]
	... 12 more
[04:02:40] [Server thread/INFO]: [AdvancedAchievements] Disabling AdvancedAchievements v5.13.4
[04:02:40] [Server thread/INFO]: [AdvancedAchievements] Remaining requests sent to the database, plugin successfully disabled.
```

**Comment by hammad-alhassan** [comment]
**and this is my database config**

```
#=============================OOO=============================#
# III-----------------------------------------------------III #
# |                    Database settings                    | #
# 3---------------------------------------------------------3 #
#=============================ooo=============================#

# Make a daily backup of your local database (if sqlite or h2).
DatabaseBackup: true

# Database type, sqlite, h2, postgresql or mysql. Do a full server restart for this to take effect.
DatabaseType: mysql

# Prefix added to the tables in the database. If you switch from the default tables names (no prefix),
# the plugin will attempt an automatic renaming. Otherwise you have to rename your tables manually.
# Do a full server restart for this to take effect.
TablePrefix: ""
  
# Specify additional options when opening a connection to a MySQL/PostgreSQL database. Start each option with &,
# for instance "&useUnicode=yes&characterEncoding=UTF-8". Make sure the key-value pairs themselves are URL encoded.
AdditionalConnectionOptions: ""

# Settings to connect to your MySQL/PostgreSQL database (ignored if sqlite).
# A PostgreSQL database address will be similar to jdbc:postgresql://localhost:5432/minecraft
DatabaseAddress: "eu01-sql.pebblehost.com"
DatabaseUser: customer_99061_data
DatabasePassword: ********
  
```

**Comment by PyvesB** [comment]
Hello @hammad-alhassan,

You have to specify the actual database name at the end of the address, for example `jdbc:mysql://localhost:3306/minecraft`. 😉 

Hope this helps!

**Comment by hammad-alhassan** [comment]
hi 
i tried everything with no luck ,could you send me the correct way to do it and this is my database info that i use for all my other plugins 

**Database Host :** eu01-sql.pebblehost.com
**Database Name :** customer_99061_data
**Database Username :** customer_99061_data
**Port :** 3306
**Database Password :** xxxxxxxxxxx

**Comment by hammad-alhassan** [comment]
thank you now its working with these settings 
DatabaseAddress: **"jdbc:mysql://sql.pebblehost.com/customer_99061_data"**
DatabaseUser: customer_99061_data
DatabasePassword: ********
