### ISSUE TITLE
Could not pass event PlayerPickupItemEvent

### ISSUE THREAD

**Issue by zephirox58** [PyvesB/AdvancedAchievements#666]
[19:18:14] [Server thread/ERROR]: Could not pass event PlayerPickupItemEvent to AdvancedAchievements v5.14.1
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_232]
	at java.lang.Integer.parseInt(Integer.java:592) ~[?:1.8.0_232]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_232]
	at com.hm.achievement.utils.RewardParser.getItemAmount(RewardParser.java:266) ~[?:?]
	at com.hm.achievement.utils.RewardParser.getItemReward(RewardParser.java:175) ~[?:?]
	at com.hm.achievement.utils.StatisticIncreaseHandler.checkThresholdsAndAchievements(StatisticIncreaseHandler.java:89) ~[?:?]
	at com.hm.achievement.listener.statistics.AbstractListener.updateStatisticAndAwardAchievementsIfAvailable(AbstractListener.java:56) ~[?:?]
	at com.hm.achievement.listener.statistics.PickupsListener.onPlayerPickupItem(PickupsListener.java:38) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1491.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-238]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-238]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-238]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.EntityItem.pickup(EntityItem.java:352) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.EntityHuman.c(EntityHuman.java:480) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.EntityHuman.movementTick(EntityHuman.java:453) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2322) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.EntityHuman.tick(EntityHuman.java:165) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:426) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.PlayerConnection.tick(PlayerConnection.java:146) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:260) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1255) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-238]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-238]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

Someone can help me ? my console spam this error message

**Comment by PyvesB** [comment]
Hi @zephirox58, this seems like an error in your configuration file, could you please share it?

**Comment by zephirox58** [comment]
https://pastebin.com/h370Y7iw

like a pastin is good ?

**Comment by PyvesB** [comment]
You're missing the count for the [item reward](https://github.com/PyvesB/AdvancedAchievements/wiki/Rewards#item) of the `Militant ecologiste` achievement. 😉

**Comment by zephirox58** [comment]
thanks a lot :D

**Comment by PyvesB** [comment]
You're welcome! Closing this issue. 😄

**Comment by PyvesB** [comment]
I've just pushed a fix so that the plugin defaults to 1 if the item count is missing, rather than throwing an error!
