### ISSUE TITLE
Issue on Data long

### ISSUE THREAD

**Issue by PoulpinSky** [PyvesB/AdvancedAchievements#668]
I, can you fix this error ?

```
[20:39:43 ERROR]: [AdvancedAchievements] Database write error while batching statistic updates:
java.sql.BatchUpdateException: Data truncation: Data too long for column 'blockid' at row 1
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212]
at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:1060) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970) ~[patched_1.12.2.jar:git-Paper-1618]
at com.hm.achievement.db.AsyncCachedRequestsSender.lambda$sendBatchedRequests$0(AsyncCachedRequestsSender.java:78) ~[?:?]
at com.hm.achievement.db.SQLWriteOperation.attemptWrites(SQLWriteOperation.java:45) ~[?:?]
at com.hm.achievement.db.AsyncCachedRequestsSender.sendBatchedRequests(AsyncCachedRequestsSender.java:83) ~[?:?]
at com.hm.achievement.db.AsyncCachedRequestsSender.run(AsyncCachedRequestsSender.java:51) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1618]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1618]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'blockid' at row 1
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3971) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1552) ~[patched_1.12.2.jar:git-Paper-1618]
at com.mysql.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:1034) ~[patched_1.12.2.jar:git-Paper-1618]
... 11 more
```

Thanks

**Comment by PoulpinSky** [comment]
We are in 229 charactere in one of our case...

**Comment by PyvesB** [comment]
Hello @PoulpinSky, when grouping sub-categories together, the maximum length of the resulting key is 191 characters long when using MySQL. 😉

**Comment by PoulpinSky** [comment]
You can't up this value ?

**Comment by PyvesB** [comment]
Well, I could, but the plugin would no longer work at all for users of MySQL 5.6 and older (see #534). MySQL 5.6 is still technically supported until February 2021, so I would rather not drop support in Advanced Achievements before then.

**Comment by PyvesB** [comment]
FYI, the next version of the plugin will include a configuration parameter to change the maximum size. 😉
