### ISSUE TITLE
BUG report

### ISSUE THREAD

**Issue by MERRYACS** [PyvesB/AdvancedAchievements#704]
Hello
When I do /aach add 1 test 哈
The error shows up:[09:30:30] [Server thread/ERROR]: Could not pass event PlayerAdvancedAchievementEvent to AdvancedAchievements v5.15.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at com.hm.achievement.utils.StatisticIncreaseHandler.checkThresholdsAndAchievements(StatisticIncreaseHandler.java:95) [AdvancedAchievements.jar:?]
	at com.hm.achievement.command.executable.AddCommand.onExecuteForPlayer(AddCommand.java:75) [AdvancedAchievements.jar:?]
	at com.hm.achievement.command.executable.AbstractParsableCommand.onExecute(AbstractParsableCommand.java:55) [AdvancedAchievements.jar:?]
	at com.hm.achievement.command.executable.AbstractCommand.execute(AbstractCommand.java:49) [AdvancedAchievements.jar:?]
	at com.hm.achievement.command.executor.PluginCommandExecutor.onCommand(PluginCommandExecutor.java:55) [AdvancedAchievements.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1399) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1234) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.IllegalArgumentException: key
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:72) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	at com.hm.achievement.listener.PlayerAdvancedAchievementListener.onPlayerAdvancedAchievementReception(PlayerAdvancedAchievementListener.java:173) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
	... 24 more

Server information:
1.12.2 Spigot
Online mode
AACH version:5.15.1

Config setting:
Custom:
  test:
    11:
      Goal: 完成所有滑稽成就
      Message: 你已解锁称号 - 滑稽
      Name: 滑稽成就
      DisplayName: 这是测试
      Reward:
        Command: say test ok

Sorry for my bad English and
Thank you.

**Comment by PyvesB** [comment]
Hello @MERRYACS, I cannot reproduce, can you please share your full configuration? 😉

**Comment by MERRYACS** [comment]
https://pastebin.com/Z501QuEH

**Comment by MERRYACS** [comment]
I just realized i Can't put the Name as Chinese, otherwise shows error

**Comment by PyvesB** [comment]
> I just realized i Can't put the Name as Chinese, otherwise shows error

Yes, exactly, that's the problem! Note that Advanced Achievements itself works fine with Chinese characters, but Spigot's own internal advancement system (which Advanced Achievements integrates with if you run a Minecraft 1.12+ server) imposes a strict set of characters, `[a-z0-9/._-]`.

I've updated [the Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki/FAQ-(Frequently-Asked-Questions)) accordingly, but I don't believe there's any other action to take here. 😉
