### ISSUE TITLE
plugin disabling after changes i made 

### ISSUE THREAD

**Issue by ca9an** [PyvesB/AdvancedAchievements#730]
plugin disabling after changes i made and i cant figure out why.i only add these lines

 zombie|wither_skeleton|stray|husk|zombie_villager|skeleton_horse|zombie_horse|skeleton|zombie|pig_zombie:
    1:
      Goal:
      Message: 
      Name:

**Comment by PyvesB** [comment]
Hello @ca9an,

The `Goal`, `Message` and `Name` parameters are missing their values, the plugin cannot simply not work without them. 😉

**Comment by ca9an** [comment]
<img width="765" alt="disable" src="https://user-images.githubusercontent.com/64966557/81316880-d0bf9f00-9094-11ea-86bd-268af3a48e3c.png">
i only add these lines and it still disabling and this is the log:
[18:26:03] [Server thread/INFO]: Hydosia issued server command: /aa reload
[18:26:03] [Server thread/ERROR]: Cannot load plugins\AdvancedAchievements\config.yml
org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 330, column 14:
          Message: bom bom
                 ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:178) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:160) ~[patched_1.12.2.jar:git-Paper-1618]
	at com.hm.achievement.command.executable.ReloadCommand.onExecute(ReloadCommand.java:80) ~[?:?]
	at com.hm.achievement.command.executable.AbstractCommand.execute(AbstractCommand.java:49) ~[?:?]
	at com.hm.achievement.command.executor.PluginCommandExecutor.onCommand(PluginCommandExecutor.java:55) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_231]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_231]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'string', line 330, column 14:
          Message: bom bom
                 ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:872) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:557) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:227) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:249) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:240) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:249) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:240) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:140) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) ~[patched_1.12.2.jar:git-Paper-1618]
	... 23 more
[18:26:03] [Server thread/ERROR]: [AdvancedAchievements] A non recoverable error was encountered while reloading the plugin, disabling it:
org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 330, column 14:
          Message: bom bom
                 ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) ~[patched_1.12.2.jar:git-Paper-1618]
	at com.hm.achievement.file.CommentedYamlConfiguration.loadConfiguration(CommentedYamlConfiguration.java:139) ~[?:?]
	at com.hm.achievement.command.executable.ReloadCommand.onExecute(ReloadCommand.java:83) ~[?:?]
	at com.hm.achievement.command.executable.AbstractCommand.execute(AbstractCommand.java:49) ~[?:?]
	at com.hm.achievement.command.executor.PluginCommandExecutor.onCommand(PluginCommandExecutor.java:55) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_231]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_231]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'string', line 330, column 14:
          Message: bom bom
                 ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:872) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:557) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:227) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:249) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:240) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:249) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:240) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:140) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) ~[patched_1.12.2.jar:git-Paper-1618]
	... 21 more
[18:26:03] [Server thread/INFO]: [AdvancedAchievements] Disabling AdvancedAchievements v6.0.0
[18:26:03] [Server thread/INFO]: [AdvancedAchievements] Remaining requests sent to the database, plugin successfully disabled.

**Comment by PyvesB** [comment]
Are you missing a space after `Goal`?

**Comment by ca9an** [comment]
i always think this  cant be the problem but it is and i solve it. thank you
