### ISSUE TITLE
/aa generate not working on paperspigot 1.16.1 - achievements database not present at "L"

### ISSUE THREAD

**Issue by Camillo82** [PyvesB/AdvancedAchievements#769]
:information_source: **Basic information**

* Advanced Achievements version: 6.1.2.
* Minecraft version: paperspigot 1.16.1
* [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/AdvancedAchievements/issues) searched: yes

:beetle: **Description**

:page_facing_up: **Server logs**

at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383) ~[patched_1.16.1.jar:git-Paper-24]
at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378) ~[patched_1.16.1.jar:git-Paper-24]
at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383) ~[patched_1.16.1.jar:git-Paper-24]
at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378) ~[patched_1.16.1.jar:git-Paper-24]
at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383) ~[patched_1.16.1.jar:git-Paper-24]
at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378) ~[patched_1.16.1.jar:git-Paper-24]
at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383) ~[patched_1.16.1.jar:git-Paper-24]
at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378) ~[patched_1.16.1.jar:git-Paper-24]
at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:383) ~[patched_1.16.1.jar:git-Paper-24]
at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378) ~[patched_1.16.1.jar:git-Paper-24]
at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:358) ~[patched_1.16.1.jar:git-Paper-24]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:158) ~[patched_1.16.1.jar:git-Paper-24]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[patched_1.16.1.jar:git-Paper-24]
at com.google.gson.Gson.getAdapter(Gson.java:423) ~[patched_1.16.1.jar:git-Paper-24]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115) ~[patched_1.16.1.jar:git-Paper-24]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164) ~[patched_1.16.1.jar:git-Paper-24]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[patched_1.16.1.jar:git-Paper-24]
at com.google.gson.Gson.getAdapter(Gson.java:423) ~[patched_1.16.1.jar:git-Paper-24]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115) ~[patched_1.16.1.jar:git-Paper-24]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164) ~[patched_1.16.1.jar:git-Paper-24]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[patched_1.16.1.jar:git-Paper-24]
at com.google.gson.Gson.getAdapter(Gson.java:423) ~[patched_1.16.1.jar:git-Paper-24]
````

````

:wrench: **Configuration**

````

````

**Comment by PyvesB** [comment]
Hello @Camillo82,

Advancement generation code in Advanced Achievements has not changed much in recent years and has worked fine since Minecraft 1.12. The [Minecraft 1.16 changelog](https://minecraft.gamepedia.com/Java_Edition_1.16) does not describe any breaking changes in the way advancements are handled.

Consider the following simple bit of code that generates an advancement from within a plugin:

````
UnsafeValues unsafeValues = Bukkit.getUnsafe();
NamespacedKey namespacedKey = new NamespacedKey(this, "somekey");
String json = "{\n" + 
		"  \"criteria\":{\n" + 
		"    \"aach_handled\":{\n" + 
		"      \"trigger\":\"minecraft:impossible\"\n" + 
		"    }\n" + 
		"  },\n" + 
		"  \"requirements\":[\n" + 
		"    [\n" + 
		"      \"aach_handled\"\n" + 
		"    ]\n" + 
		"  ],\n" + 
		"  \"display\":{\n" + 
		"    \"icon\":{\n" + 
		"      \"item\":\"minecraft:book\"\n" + 
		"    },\n" + 
		"    \"title\":\"Some title\",\n" + 
		"    \"description\":\"\",\n" + 
		"    \"frame\":\"goal\",\n" + 
		"    \"announce_to_chat\":false,\n" + 
		"    \"background\":\"minecraft:textures/item/book.png\"\n" + 
		"  }\n" + 
		"}";
unsafeValues.loadAdvancement(namespacedKey, json);
````

This worked fine in previous versions of Minecraft, but now blows up with 1.16 versions of Spigot. This causes a StackOverflow error:
````
java.lang.StackOverflowError
	at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111) ~[craftbukkit16.jar:git-Spigot-758abbe-8dc1da1]
	at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:546) ~[craftbukkit16.jar:git-Spigot-758abbe-8dc1da1]
	at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111) ~[craftbukkit16.jar:git-Spigot-758abbe-8dc1da1]
	at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:553) ~[craftbukkit16.jar:git-Spigot-758abbe-8dc1da1]
	at com.google.gson.internal.$Gson$Types.canonicalize($Gson$Types.java:111) ~[craftbukkit16.jar:git-Spigot-758abbe-8dc1da1]
	at com.google.gson.internal.$Gson$Types$WildcardTypeImpl.<init>($Gson$Types.java:546) ~[craftbukkit16.jar:git-Spigot-758abbe-8dc1da1]
...
````

I can't see anything obviously wrong, the above code has always worked in the past and the JSON being used is valid. This looks like a Spigot bug to me.  Could you please report it on the [Spigot issue tracker](https://hub.spigotmc.org/jira) with the information available here?

**Comment by Camillo82** [comment]
It is working now, probably it was related to the spigot bug.

**Comment by PyvesB** [comment]
Good to hear, thanks for the coming back to me!
