### ISSUE TITLE
Error on entity death.

### ISSUE THREAD

**Issue by Zilacon** [PyvesB/AdvancedAchievements#780]
:information_source: **Basic information**

* Advanced Achievements version: 6.0.0
* Minecraft version: 1.7.10 
* [Wiki](https://github.com/PyvesB/AdvancedAchievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/AdvancedAchievements/issues) searched: yes

:beetle: **Description**

Use plugin on a 1.7.10 server like thermos or crucible.
Have a modded entity die?
Get this error:

:page_facing_up: **Server logs**

```
[13:24:16 ERROR]: Could not pass event EntityDeathEvent to AdvancedAchievements v6.0.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[JavaPluginLoader$1.class:1.7.10-3.1]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[TimedEventExecutor.class:1.7.10-3.1]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-3.1]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:531) [SimplePluginManager.class:1.7.10-3.1]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:516) [SimplePluginManager.class:1.7.10-3.1]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:360) [CraftEventFactory.class:1.7.10-3.1]
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1066) [sv.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:972) [sv.class:?]
	at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:145) [wf.class:?]
	at moze_intel.projecte.gameObjs.items.tools.PEToolBase.attackAOE(PEToolBase.java:447) [PEToolBase.class:?]
	at moze_intel.projecte.gameObjs.items.tools.RedKatar.doExtraFunction(RedKatar.java:98) [RedKatar.class:?]
	at moze_intel.projecte.network.packets.KeyPressPKT$Handler.onMessage(KeyPressPKT.java:94) [KeyPressPKT$Handler.class:?]
	at moze_intel.projecte.network.packets.KeyPressPKT$Handler.onMessage(KeyPressPKT.java:47) [KeyPressPKT$Handler.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) [SimpleChannelHandlerWrapper.class:1.7.10-3.1]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) [SimpleChannelHandlerWrapper.class:1.7.10-3.1]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-3.1]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1033) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:852) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:702) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:821) [?:1.8.0_252]
Caused by: java.lang.NoSuchMethodError: org/bukkit/entity/Entity.getCustomName()Ljava/lang/String; (loaded from jar:file:/home/apoc/Servers/TLEG/TLEG.jar!/org/bukkit/entity/Entity.class by net.minecraft.launchwrapper.LaunchClassLoader@c117b220) called from class com.hm.achievement.listener.statistics.KillsListener (loaded from file:/home/apoc/Servers/TLEG/plugins/AdvancedAchievements.jar by org.bukkit.plugin.java.PluginClassLoader@b6491a6a).
	at com.hm.achievement.listener.statistics.KillsListener.onEntityDeath(KillsListener.java:56) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor230.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307) ~[JavaPluginLoader$1.class:1.7.10-3.1]
	... 37 more
```

**Comment by PyvesB** [comment]
Hello @Zilacon, thanks for the report, will look into it. 😉
