### ISSUE TITLE
1.16 there was a mistake after finishing the achievement    报错

### ISSUE THREAD

**Issue by suningy** [PyvesB/AdvancedAchievements#784]
[14:45:05 INFO]: [AdvancedAchievements] Player CrispyTannin received the achievement: enderpearls_10 (小心脚下)
[14:45:48 ERROR]: Could not pass event EntityDamageByEntityEvent to DangerousSurvival v1.0
java.lang.NullPointerException: null
        at survivalpackage.survivalmain.entityHitByPlayer(survivalmain.java:8935) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor178.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:245) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1022) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:909) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:865) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1054) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity0(EntityLiving.java:1826) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at net.minecraft.server.v1_16_R1.EntityHuman.damageEntity0(EntityHuman.java:844) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity(EntityLiving.java:1159) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at net.minecraft.server.v1_16_R1.EntityHuman.damageEntity(EntityHuman.java:761) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at net.minecraft.server.v1_16_R1.EntityPlayer.damageEntity(EntityPlayer.java:836) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at net.citizensnpcs.nms.v1_16_R1.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:155) ~[?:?]
        at net.minecraft.server.v1_16_R1.EntityEnderPearl.a(EntityEnderPearl.java:29) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at net.minecraft.server.v1_16_R1.IProjectile.a(IProjectile.java:125) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at net.minecraft.server.v1_16_R1.EntityEnderPearl.a(EntityEnderPearl.java:34) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at net.minecraft.server.v1_16_R1.EntityProjectile.tick(EntityProjectile.java:53) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at net.minecraft.server.v1_16_R1.EntityEnderPearl.tick(EntityEnderPearl.java:93) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at net.minecraft.server.v1_16_R1.WorldServer.entityJoinedWorld(WorldServer.java:832) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at net.minecraft.server.v1_16_R1.World.a(World.java:932) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at net.minecraft.server.v1_16_R1.WorldServer.doTick(WorldServer.java:526) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1353) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[Paper-1.16.1-b26.jar:git-Paper-26]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
报错  版本是1.16.1  请尽快能完全兼容1.16.1哦！非常感谢！thanks！

**Comment by PyvesB** [comment]
Hello @suningy,

This is not an error with Advanced Achievements, but rather with DangerousSurvival. 😉
