### ISSUE TITLE
EventException - Could not pass event InventoryClickEvent

### ISSUE THREAD

**Issue by mibby** [PyvesB/AdvancedAchievements#86]
AdvancedAchievements v3.0.5 compiled as of commit https://github.com/PyvesB/AdvancedAchievements/commit/f0263d9899587a7331e2876396a2d488f4fe83b0

Default config.
http://paste.ubuntu.com/23377863/

Error occurs when clicking on the 'other achievements' category option in the GUI.

```
[01:12:41 ERROR]: Could not pass event InventoryClickEvent to AdvancedAchievements v3.0.5
org.bukkit.event.EventException
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.10.2.jar:git-Paper-898]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.10.2.jar:git-Paper-898]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.10.2.jar:git-Paper-898]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.10.2.jar:git-Paper-898]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.10.2.jar:git-Paper-898]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1909) [patched_1.10.2.jar:git-Paper-898]
        at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [patched_1.10.2.jar:git-Paper-898]
        at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [patched_1.10.2.jar:git-Paper-898]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.10.2.jar:git-Paper-898]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_112]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [patched_1.10.2.jar:git-Paper-898]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:802) [patched_1.10.2.jar:git-Paper-898]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-898]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:734) [patched_1.10.2.jar:git-Paper-898]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:633) [patched_1.10.2.jar:git-Paper-898]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
Caused by: java.lang.NumberFormatException: For input string: "yourAch1"
        at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_112]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_112]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_112]
        at com.hm.achievement.command.ListCommand.createCategoryGUINormal(ListCommand.java:531) ~[?:?]
        at com.hm.achievement.listener.ListGUIListener.onInventoryClick(ListGUIListener.java:69) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor507.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.10.2.jar:git-Paper-898]
        ... 16 more
```

**Comment by PyvesB** [comment]
Hello,

Thank you for the bug report, this must have been introduced during one of the clean-up/refactor commits and the current repository version has not been correctly tested yet. I will fix this as soon as possible. ;-)

Cheers,

Pyves
