### ISSUE TITLE
Error Registering Permissions

### ISSUE THREAD

**Issue by EnderSandman** [PyvesB/AdvancedAchievements#89]
[15:00:46] [Server thread/INFO]: [AdvancedAchievements] Enabling AdvancedAchievements v3.0.5
[15:00:46] [Server thread/INFO]: [AdvancedAchievements] Backing up and loading configuration files...
[15:00:46] [Server thread/INFO]: [AdvancedAchievements] Loading configs, registering permissions and initialising command modules...
[15:00:46] [Server thread/ERROR]: Error occurred while enabling AdvancedAchievements v3.0.5 (Is it up to date?)
java.lang.NullPointerException
        at com.hm.achievement.AdvancedAchievements.registerPermissions(AdvancedAchievements.java:972) ~[?:?]
        at com.hm.achievement.AdvancedAchievements.configurationLoad(AdvancedAchievements.java:501) ~[?:?]
        at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:203) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.10.2.jar:git-Spigot-047f737-9558f31]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.10.2.jar:git-Spigot-047f737-9558f31]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.2.jar:git-Spigot-047f737-9558f31]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot-1.10.2.jar:git-Spigot-047f737-9558f31]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot-1.10.2.jar:git-Spigot-047f737-9558f31]
        at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [spigot-1.10.2.jar:git-Spigot-047f737-9558f31]
        at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [spigot-1.10.2.jar:git-Spigot-047f737-9558f31]
        at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [spigot-1.10.2.jar:git-Spigot-047f737-9558f31]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [spigot-1.10.2.jar:git-Spigot-047f737-9558f31]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-047f737-9558f31]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

**Comment by EnderSandman** [comment]
Sqllite DB file was currupt. I deleted it and restarted the server and now it all works.

**Comment by PyvesB** [comment]
Okay, let me know if you have any more issues. ;-)

Cheers,

Pyves
